### PR TITLE
Fix parsing issue with default in export clause specifier

### LINKED ISSUE #960: javascript:ParsingError with export
**I want to report a bug.**

**SonarJS version:** 4.1 (build 6085)<br>
**SonarQube version:** Version 6.7 (build 33306) <br>

**Rule key:** javascript:ParsingError

**Logs**
```
15:35:13.752 ERROR - Unable to parse file: .../test.js
15:35:13.753 ERROR - Parse error at line 1 column 9:

1: export {default as template} from './otherFile.html';
            ^
```

**Expected behavior**
We updated today to the latest Version of SonarJS und after the scan we got multiple parse errors. In the previous it worked as expected - the files got parsed without errors. Unfortunately we don't know our previous version number.

### PR DESCRIPTION
**Pull request by saberduck**
Fixes #960

### CODE REVIEW

File: javascript-frontend/src/main/java/org/sonar/javascript/parser/JavaScriptGrammar.java [hunk 1]
```diff
@@ -1324,6 +1324,8 @@ public NamedImportExportClauseTree EXPORT_LIST() {
   public SpecifierTree EXPORT_SPECIFIER() {
     return b.<SpecifierTree>nonterminal(Kind.EXPORT_SPECIFIER)
       .is(b.firstOf(
+        f.exportSpecifier(f.identifierReference(b.token(JavaScriptKeyword.DEFAULT)),  b.token(EcmaScriptLexer.AS), IDENTIFIER_NAME()),
```
Comment (vilchik-elena) [inline javascript-frontend/src/main/java/org/sonar/javascript/parser/JavaScriptGrammar.java]: two spaces :)

Comment (saberduck) [reply javascript-frontend/src/main/java/org/sonar/javascript/parser/JavaScriptGrammar.java]: good eye!
