### PR TITLE
Fix FP on S1128 for "jsx" import used in "Emotion" pragma

### LINKED ISSUE #1273: FP S1128 for "jsx" import used in "Emotion" pragma
```
/** @jsx jsx */
import { jsx } from '@emotion/core'
```

See docs https://emotion.sh/docs/css-prop

Reported in [community thread](https://community.sonarsource.com/t/jsx-pragma-does-not-prevent-unnecessary-import-warning/7790).

### PR DESCRIPTION
**Pull request by yassin-kammoun-sonarsource**
Fixes #1273

### CODE REVIEW

File: eslint-bridge/src/rules/unused-import.ts [hunk 1]
```diff
@@ -27,14 +27,26 @@ const EXCLUDED_IMPORTS = ['React'];
...
+        const { source } = node as estree.ImportDeclaration;
         const variables = context.getDeclaredVariables(node);
         for (const variable of variables) {
-          if (!EXCLUDED_IMPORTS.includes(variable.name) && variable.references.length === 0) {
+          if (
+            !EXCLUDED_IMPORTS.includes(variable.name) &&
+            variable.references.length === 0 &&
+            variable.name !== 'jsx' &&
+            source.value !== '@emotion/core' &&
+            !isJsxPragmaSet
```
Comment (guillaume-dequenne-sonarsource) [inline eslint-bridge/src/rules/unused-import.ts:48]: To me it's a bit unclear what we are trying to exclude.
Do we really want to exclude all import of `jsx` names and all imports from `@emotion/core` specifically?

From my understanding of the [documentation](https://emotion.sh/docs/css-prop#jsx-pragma), it's really the pragma comment that makes us want to ignore this pattern (and it seems like it being absent would cause problems with the Emotion library). 

If I'm mistaken and there are other patterns (maybe in another version of this framework or something) that we actually want to exclude (maybe just to be safe...), I think it'd be worth it to have explicit tests for them.

**Review by guillaume-dequenne-sonarsource — CHANGES_REQUESTED** [review]
Looks good but please have a look at my comment: I think we can either make the condition a bit more strict or be more explicit about the pattern we exclude.

File: eslint-bridge/src/rules/unused-import.ts (hunk 1 above)
Comment (yassin-kammoun-sonarsource) [reply eslint-bridge/src/rules/unused-import.ts]: > To me it's a bit unclear what we are trying to exclude.
> Do we really want to exclude all import of `jsx` names and all imports from `@emotion/core` specifically?

You are right! It's not specific to `@emotion/core`. I just relaxed that condition.

> If I'm mistaken and there are other patterns (maybe in another version of this framework or something) that we actually want to exclude (maybe just to be safe...), I think it'd be worth it to have explicit tests for them.

I added a test case for "any" imported source.

**Review by guillaume-dequenne-sonarsource — APPROVED** [review]
lgtm
