### PR TITLE
Add quick fix for S1110 (no-redundant-parentheses)

### LINKED ISSUE #3001: Add quick fix for S1110: Redundant pairs of parentheses should be removed
SonarJS rule.

### PR DESCRIPTION
**Pull request by vilchik-elena**
Fixes #3001

### CODE REVIEW

File: eslint-bridge/src/quickfix.ts [hunk 1]
```diff
@@ -51,6 +51,7 @@ const quickFixRules = new Set([
   'no-non-null-assertion',
 
   // sonarjs
+  'no-redundant-parentheses',
   'no-commented-code',
```
Comment (yassin-kammoun-sonarsource) [inline eslint-bridge/src/quickfix.ts:55]:
```suggestion
  'no-commented-code',
  'no-redundant-parentheses',
```
