### PR TITLE
Add quick fix for S4138 ('prefer-for-of')

### LINKED ISSUE #3023: Add quick fix for S4138: "for of" should be used with Iterables
typescript-eslint rule.

### PR DESCRIPTION
**Pull request by yassin-kammoun-sonarsource**
Fixes #3023

### CODE REVIEW

File: eslint-bridge/src/linter.ts [hunk 1]
```diff
@@ -121,6 +114,13 @@ export class LinterWrapper {
       );
     }
 
+    externalRuleDecorators.forEach(externalRuleDecorator => {
+      this.linter.defineRule(
+        externalRuleDecorator.ruleKey,
+        externalRuleDecorator.decorate(this.linter.getRules().get(externalRuleDecorator.ruleKey)!),
+      );
+    });
+
```
Comment (yassin-kammoun-sonarsource) [inline eslint-bridge/src/linter.ts:123]: Moved rule decorating after defining TypeScript ESLint rules.

File: its/ruling/src/test/expected/ts/console/typescript-S2814.json [hunk 2]
```diff
@@ -1,5 +0,0 @@
-{
-'console:src/views/FunctionsView/FunctionPopup/data.tsx':[
-4,
-],
-}
```
Comment (yassin-kammoun-sonarsource) [inline its/ruling/src/test/expected/ts/console/typescript-S2814.json:5]: The disappearance of this issue highlights an interesting bug that we missed when first introducing a decorator for S2814 ('no-redeclare'). The decorated rule was actually never triggered, only the undecorated one was. Here is what happened:

1. ESLint 'no-redeclare' was first enabled
2. ESLint 'no-redeclare' was then decorated
3. TypeScript ESLint  'no-redeclare' overwrote everything

This remained unnoticed because the test suite was not using the analysis pipeline of eslint-bridge. Postponing when decoration occurs is a consequence of why this issue is no longer reported as the decorated rule is now triggered.

File: eslint-bridge/tests/rules/decorators/prefer-for-of-decorator.test.ts [hunk 3]
```diff
@@ -0,0 +1,195 @@
...
+  ],
+  invalid: [
+    {
+      code: `for (let i = 0; i < arr.length; ++i) console.log(arr[i]);`,
+      errors: [
+        {
+          suggestions: [
+            {
+              desc: `Replace with "for of" loop`,
+              output: `for (const element of arr) console.log(element);`,
```
Comment (vilchik-elena) [inline eslint-bridge/tests/rules/decorators/prefer-for-of-decorator.test.ts:41]: what if variable with name `element` already exists?

**Review by vilchik-elena — CHANGES_REQUESTED** [review]

File: eslint-bridge/tests/rules/decorators/prefer-for-of-decorator.test.ts (hunk 3 above)
Comment (yassin-kammoun-sonarsource) [reply eslint-bridge/tests/rules/decorators/prefer-for-of-decorator.test.ts:41]: Indeed, I wasn't sure what to do to prevent this problem: generating a random name, inserting a syntactically invalid placeholder, ...

Do you have any suggestions ?

Comment (vilchik-elena) [reply eslint-bridge/tests/rules/decorators/prefer-for-of-decorator.test.ts:41]: we can simply not provide the fix if name is occupied :)

File: its/ruling/src/test/expected/ts/console/typescript-S2814.json (hunk 2 above)
Comment (yassin-kammoun-sonarsource) [reply its/ruling/src/test/expected/ts/console/typescript-S2814.json:5]: What does "this problem" refer to here ?

**Review by vilchik-elena — CHANGES_REQUESTED** [review]

File: eslint-bridge/src/linter.ts (hunk 1 above)
Comment (vilchik-elena) [reply eslint-bridge/src/linter.ts:123]: And how did you discover this bug?

File: eslint-bridge/src/rules/decorators/prefer-for-of-decorator.ts [hunk 4]
```diff
@@ -0,0 +1,93 @@
...
+    }
+    context.report({
+      ...reportDescriptor,
+      suggest,
+    });
+  });
+}
+
+function isFixable(context: Rule.RuleContext) {
+  return context.getScope().references.every(reference => reference.identifier.name !== element);
```
Comment (vilchik-elena) [inline eslint-bridge/src/rules/decorators/prefer-for-of-decorator.ts:49]: https://eslint.org/docs/developer-guide/scope-manager-interface#references

> The array of all references on this scope. This does not include references in child scopes.

File: eslint-bridge/src/linter.ts (hunk 1 above)
Comment (yassin-kammoun-sonarsource) [reply eslint-bridge/src/linter.ts:123]: Some tests were failing because the linter was trying to decorate a (TypeScript ESLint) rule that wasn't defined yet.

**Review by vilchik-elena — APPROVED** [review]
