### PR TITLE
Fix parsing of imports when identifier matches flow keywords

### LINKED ISSUE #995: E6 Modules named import variable "types" treated as non-existent
**SonarJS version:** 4.1 (build 6085)
**SonarQube version:** Version 7.1 (build 11001)<br>

**Rule key:** javascript:S3827

**Reproducer** 
```
import { types } from 'some/path/here';

export default (state = {}, action) => {
    switch (action.type) {
    case types.SOMETHING:
        return { test: true };
    default:
        return state;
    }
};
```

**Result**
Line 5: "types" does not exist. Change its name or declare it so that its usage doesn't result in a "ReferenceError".

**Expected behavior**
No errors at all.

If i rename the import like the example below Sonarqube finds no errors.
```
import { types as someTypes } from 'some/path/here';
```

### PR DESCRIPTION
**Pull request by saberduck**
Fixes #995

### CODE REVIEW

File: javascript-frontend/src/main/java/org/sonar/javascript/parser/EcmaScriptLexer.java [hunk 1]
```diff
@@ -460,7 +460,7 @@ private static void lexical(LexerlessGrammarBuilder b) {
 
     // Flow
     b.rule(OPAQUE).is(SPACING, b.token(GenericTokenType.IDENTIFIER, "opaque"));
-    b.rule(TYPE).is(SPACING, b.token(GenericTokenType.IDENTIFIER, "type"));
+    b.rule(TYPE).is(SPACING, b.token(GenericTokenType.IDENTIFIER, "type"), b.nextNot(LETTER_OR_DIGIT));
```
Comment (vilchik-elena) [inline javascript-frontend/src/main/java/org/sonar/javascript/parser/EcmaScriptLexer.java]: @saberduck we should use `word` everywhere

**Comment by vilchik-elena** [comment]
@saberduck could you also add test that there is no FP for javascript:S3827?
