### PR TITLE
Fix parsing of regular expression literals for JDK 9

### LINKED ISSUE #801: Fix parsing of Vue under JDK 9
```
<script>
x
</script>
<style>
</style>
```

### PR DESCRIPTION
**Pull request by Godin**
This is required due to https://bugs.openjdk.java.net/browse/JDK-8189343

Fixes #801

### CODE REVIEW

File: javascript-frontend/src/test/java/org/sonar/javascript/parser/lexical/RegularExpressionLiteralTest.java [hunk 1]
```diff
@@ -37,4 +37,12 @@ public void ok() {
       .matches("/[\\B]/");
   }
 
+  @Test
+  public void cannot_contain_line_terminator() {
+    assertThat(JavaScriptTokenType.REGULAR_EXPRESSION_LITERAL)
+      .notMatches("/\n/")
```
Comment (vilchik-elena) [inline javascript-frontend/src/test/java/org/sonar/javascript/parser/lexical/RegularExpressionLiteralTest.java]: It would be nice to add `matches("/\\n/")`

**Comment by vilchik-elena** [comment]
Thanks @Godin!
