### PR TITLE
FP S1135: surrounding accented characters should be considered

### LINKED ISSUE #2957: FP S1135: surrounding accented characters should be considered
The rule currently ignores todo occurrences iff it is surrounded by a character accepted by the regular expression [A-Za-z]. This is incorrect as the rule could reports false-positives when there are surrounding accented characters, like for example:

```javascript
class C {
  // Método que calcula a média dos números
  m() { /* ... */}
}
```

Here `Método` is flagged because the _todo_ occurrence is preceded by _é_, that is, an accented character.

Reported in https://community.sonarsource.com/t/l25-typescript-catches-todo-in-part-of-other-words/56672

### PR DESCRIPTION
**Pull request by yassin-kammoun-sonarsource**
Fixes #2957

### CODE REVIEW

File: eslint-bridge/src/rules/todo-tag.ts [hunk 1]
```diff
@@ -24,6 +24,7 @@ import { TSESTree } from '@typescript-eslint/experimental-utils';
 
 const todoMessage = 'Complete the task associated to this "TODO" comment.';
 const todoPattern = 'todo';
+const letterPattern = /[A-Za-zÀ-ÖØ-öø-ÿ]/;
```
Comment (vilchik-elena) [inline eslint-bridge/src/rules/todo-tag.ts:27]: I found this one `/[\p{Letter}]/u`. Seems more reliable and matches `ā` not matched by your regex

**Review by vilchik-elena — CHANGES_REQUESTED** [review]

**Comment by vilchik-elena** [comment]
@yassin-kammoun-sonarsource could you add a code example to the fixed issue?

File: eslint-bridge/src/rules/todo-tag.ts (hunk 1 above)
Comment (yassin-kammoun-sonarsource) [reply eslint-bridge/src/rules/todo-tag.ts]: Thanks.

**Review by vilchik-elena — APPROVED** [review]
