### PR TITLE
Add quick fix for S1186 ('no-empty-function')

### LINKED ISSUE #3005: Add quick fix for S1186: Functions should not be empty
Eslint rule. Fix available in SonarJava.

### PR DESCRIPTION
**Pull request by yassin-kammoun-sonarsource**
Fixes #3005

### CODE REVIEW

**Comment by yassin-kammoun-sonarsource** [comment]
Inspired from [EmptyMethodsCheck](https://github.com/SonarSource/sonar-java/blob/9cb487451cbb3df1ce5715128b5c65d68f4ac90a/java-checks/src/main/java/org/sonar/java/checks/EmptyMethodsCheck.java#L101-L120) (SonarJava).

File: eslint-bridge/src/rules/decorators/no-empty-function-decorator.ts [hunk 1]
```diff
@@ -0,0 +1,63 @@
...
+      const closingBrace = context
+        .getSourceCode()
+        .getLastToken(func.body, token => token.value === '}')!;
+      let commentPlaceholder: string;
+      if (openingBrace.loc.start.line === closingBrace.loc.start.line) {
+        commentPlaceholder = ` /* TODO document why this ${name} is empty */ `;
+      } else {
+        const columnOffset = closingBrace.loc.start.column;
+        const padding = ' '.repeat(columnOffset);
+        commentPlaceholder = `\n${padding}  // TODO document why this ${name} is empty\n${padding}`;
```
Comment (vilchik-elena) [inline eslint-bridge/src/rules/decorators/no-empty-function-decorator.ts:50]: I see that java impl has that, but I don't get why we need second new line. Do you?

File: eslint-bridge/tests/rules/decorators/no-empty-function-decorator.test.ts [hunk 2]
```diff
@@ -0,0 +1,115 @@
...
+      ],
+    },
+    {
+      code: `
+const obj = {
+  foo: function() {
+    }
+};
+`,
+      errors: [
```
Comment (vilchik-elena) [inline eslint-bridge/tests/rules/decorators/no-empty-function-decorator.test.ts:97]: can we add the arrow function to see what will be the name of it?

**Review by vilchik-elena — CHANGES_REQUESTED** [review]

File: eslint-bridge/src/rules/decorators/no-empty-function-decorator.ts [hunk 3]
```diff
@@ -0,0 +1,63 @@
...
+type FunctionLike =
+  | estree.ArrowFunctionExpression
+  | estree.FunctionDeclaration
+  | estree.FunctionExpression;
+
+// core implementation of this rule does not provide quick fixes
+export function decorateNoEmptyFunction(rule: Rule.RuleModule): Rule.RuleModule {
+  rule.meta!.hasSuggestions = true;
+  return interceptReport(rule, (context, reportDescriptor) => {
+    if ('node' in reportDescriptor) {
```
[the remark this answers is not in the document]
Comment (yassin-kammoun-sonarsource) [reply eslint-bridge/src/rules/decorators/no-empty-function-decorator.ts:35]: Yes, the issue won't be reported. I am starting to think that this condition is useless because once we intercept a report, we know for sure that there is a node, at least for this rule. Should I just remove the condition ?

File: eslint-bridge/src/rules/decorators/no-empty-function-decorator.ts (hunk 1 above)
Comment (yassin-kammoun-sonarsource) [reply eslint-bridge/src/rules/decorators/no-empty-function-decorator.ts:50]: No idea. [SONARJAVA-3906](https://jira.sonarsource.com/browse/SONARJAVA-3918) mentions that there are situations when a newline is needed, but I didn't see an example in the unit tests.

**Review by vilchik-elena — APPROVED** [review]
