### PR TITLE
Fix FP S1110 (`no-redundant-parentheses`): Ignore sequence expressions

### LINKED ISSUE #2995: Fix FP S1110 `no-redundant-parentheses`: Ignore sequence expressions
The rule S878 raises an issue on the use of the comma operator, in other words in presence of a sequence expression:

```javascript
foo = bar(), baz;   // issue
```

It makes, however, an exception when a sequence expression is explicitly wrapped in parentheses:

```javascript
(foo = bar(), baz); // no issues
```

On the other hand, S1110 inconsistently raises an issue when surrounding a sequence expression between parentheses.

Reported in https://community.sonarsource.com/t/s878-unexpected-use-of-comma-operator/58715

### PR DESCRIPTION
**Pull request by victor-diez-sonarsource**
Fixes #2995

### CODE REVIEW

File: eslint-bridge/src/linting/eslint/rules/no-redundant-parentheses.ts [hunk 1]
```diff
@@ -29,6 +29,18 @@ interface ParenthesesPair {
...
+/**
+ * Parts of the grammar that are required to have parens.
+ */
+const parenthesized: { [key: string]: string } = {
+  DoWhileStatement: 'test',
+  IfStatement: 'test',
+  SwitchStatement: 'discriminant',
+  WhileStatement: 'test',
+  WithStatement: 'object',
+  ArrowFunctionExpression: 'body',
```
Comment (yassin-kammoun-sonarsource) [inline eslint-bridge/src/linting/eslint/rules/no-redundant-parentheses.ts:41]: We should add test cases for the node types that are currently not covered, `SwitchStatement` and `WithStatement` if I haven't missed anything.

File: eslint-bridge/src/linting/eslint/rules/no-redundant-parentheses.ts [hunk 2]
```diff
@@ -65,13 +77,13 @@ function checkRedundantParentheses(
 
   parenthesesPairsAroundNode.forEach(parentheses => {
     context.report({
-      message: toEncodedMessage(`Remove these useless parentheses.`, [
+      message: toEncodedMessage(`Remove these redundant parentheses.`, [
```
Comment (yassin-kammoun-sonarsource) [inline eslint-bridge/src/linting/eslint/rules/no-redundant-parentheses.ts:80]: 👍

File: eslint-bridge/src/linting/eslint/rules/no-redundant-parentheses.ts [hunk 3]
```diff
@@ -103,11 +115,14 @@ function getParenthesesPairsAround(
...
   const nodeIsInConditionOfParent =
-    (parent.type === 'IfStatement' ||
-      parent.type === 'WhileStatement' ||
-      parent.type === 'DoWhileStatement') &&
-    parent.test === node;
+    parenthesized[parent.type as keyof typeof parenthesized] &&
+    node ===
+      (parent[
+        parenthesized[parent.type as keyof typeof parenthesized] as keyof estree.Node
+      ] as unknown as estree.Node);
```
Comment (yassin-kammoun-sonarsource) [inline eslint-bridge/src/linting/eslint/rules/no-redundant-parentheses.ts:125]: I think extracting `parenthesized[parent.type as keyof typeof parenthesized]` in a well-named variable would make the code more readable and also avoid duplicating this expression twice.

File: eslint-bridge/src/linting/eslint/rules/no-redundant-parentheses.ts [hunk 4]
```diff
@@ -29,6 +29,18 @@ interface ParenthesesPair {
   closingParenthesis: AST.Token;
 }
 
+/**
+ * Parts of the grammar that are required to have parens.
```
Comment (yassin-kammoun-sonarsource) [inline eslint-bridge/src/linting/eslint/rules/no-redundant-parentheses.ts:33]:
```suggestion
 * Parts of the grammar that are required to have parentheses.
```

File: eslint-bridge/src/linting/eslint/rules/no-redundant-parentheses.ts [hunk 5]
```diff
@@ -29,6 +29,18 @@ interface ParenthesesPair {
...
+ */
+const parenthesized: { [key: string]: string } = {
+  DoWhileStatement: 'test',
```
Comment (yassin-kammoun-sonarsource) [inline eslint-bridge/src/linting/eslint/rules/no-redundant-parentheses.ts:36]: I wonder whether we should add `ImportExpression`, which represents dynamic imports.

**Review by yassin-kammoun-sonarsource — CHANGES_REQUESTED** [review]

**Review by yassin-kammoun-sonarsource — APPROVED** [review]
LGTM
