### PR TITLE
Fix analysis of files with BOM character

### LINKED ISSUE #1646: Analysis fails on file with BOM
Analysis is failing when we analyze file with BOM character, seems like computed offset do not match the file 

```
ava.lang.IllegalArgumentException: 21 is not a valid line offset for pointer. File file.js has 20 character(s) at line 1
	at org.sonar.api.utils.Preconditions.checkArgument(Preconditions.java:43)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.checkValid(DefaultInputFile.java:339)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.newPointer(DefaultInputFile.java:272)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.newRange(DefaultInputFile.java:288)
	at org.sonar.plugins.javascript.eslint.EslintBridgeServer$Location.toTextRange(EslintBridgeServer.java:137)
	at org.sonar.plugins.javascript.eslint.AbstractEslintSensor.saveCpd(AbstractEslintSensor.java:267)
	at org.sonar.plugins.javascript.eslint.AbstractEslintSensor.processResponse(AbstractEslintSensor.java:204)
	at org.sonar.plugins.javascript.eslint.JavaScriptEslintBasedSensor.analyze(JavaScriptEslintBasedSensor.java:83)
	at org.sonar.plugins.javascript.eslint.JavaScriptEslintBasedSensor.analyzeFiles(JavaScriptEslintBasedSensor.java:70)
	at org.sonar.plugins.javascript.eslint.AbstractEslintSensor.execute(AbstractEslintSensor.java:115)
	at org.sonar.plugins.javascript.eslint.JavaScriptEslintBasedSensor.execute(JavaScriptEslintBasedSensor.java:44)
	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:59)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:77)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:59)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:82)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:387)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:383)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:346)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:141)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
```

### PR DESCRIPTION
**Pull request by saberduck**
Fixes #1646

### CODE REVIEW

File: eslint-bridge/src/analyzer.ts [hunk 1]
```diff
@@ -120,10 +120,22 @@ export function analyzeTypeScript(input: AnalysisInput): AnalysisResponse {
   return analyze(input, parseTypeScriptSourceFile);
 }
 
+function getFileContent(filePath: string) {
+  const fileContent = fs.readFileSync(filePath, { encoding: "utf8" });
+  return stripBom(fileContent);
+}
+
+function stripBom(s: string) {
+  if (s.charCodeAt(0) === 0xfeff) {
```
Comment (quentin-jaquier-sonarsource) [inline eslint-bridge/src/analyzer.ts]: Is it the only BOM character that we want to remove? What about BOM in [others encoding](https://en.wikipedia.org/wiki/Byte_order_mark#Byte_order_marks_by_encoding)?

Comment (saberduck) [reply eslint-bridge/src/analyzer.ts]: hm, it's a bit more complicated. In fact, we only support utf8, the encoding is hardcoded here https://github.com/SonarSource/SonarJS/blob/master/eslint-bridge/src/analyzer.ts#L126

File: eslint-bridge/tests/analyzer.test.ts [hunk 2]
```diff
@@ -117,6 +117,23 @@ describe("#analyzeJavaScript", () => {
...
     expect(issues).toHaveLength(2);
   });
+
+  it("should handle BOM", () => {
+    const filePath = join(__dirname, "./fixtures/js-project/fileWithBom.lint.js");
+
+    const cpdTokens = analyzeJavaScript({
+      filePath,
+      fileContent: undefined,
+      rules: [{ key: "no-all-duplicated-branches", configurations: [] }],
```
Comment (vilchik-elena) [inline eslint-bridge/tests/analyzer.test.ts]: do we need any rules?

File: eslint-bridge/src/analyzer.ts (hunk 1 above)
Comment (saberduck) [reply eslint-bridge/src/analyzer.ts]: we are going to fix issue with other encodings in #1657 . We are removing BOM from utf-16, because this is internal string representation in Node.js, so UTF-8 bom is converted to this one once the file is loaded to string

File: eslint-bridge/tests/analyzer.test.ts (hunk 2 above)
Comment (saberduck) [reply eslint-bridge/tests/analyzer.test.ts]: indeed, removed
