### PR TITLE
Refactor parser.ts and fix `allowTsParserJsFiles` for `.vue` files

### LINKED ISSUE #2684: Apply `allowTsParserJsFiles` internal property to `.vue` files parsing
currently even if `allowTsParserJsFiles` is set to `false`, `.vue` files will be parsed with TypeScript parser.

### PR DESCRIPTION
**Pull request by vilchik-elena**
Fixes #2684 (during refactoring I took the opportunity to fix #2684)

### CODE REVIEW

File: eslint-bridge/src/parser.ts [hunk 1]
```diff
@@ -17,182 +17,151 @@
...
+  usingBabel = false,
+  parserOption?: string,
+  sourceType: 'script' | 'module' = 'module',
+) {
+  const options: Linter.ParserOptions = {
+    tokens: true,
+    comment: true,
+    loc: true,
+    range: true,
+    ecmaVersion: 2018,
```
Comment (yassin-kammoun-sonarsource) [inline eslint-bridge/src/parser.ts:126]: We should start thinking about updating this version.

**Review by yassin-kammoun-sonarsource — APPROVED** [review]
