### PR TITLE
Fix FP S6749 (`jsx-no-useless-fragment`): Ignore empty React fragments

### LINKED ISSUE #4192: Fix FP S6749 (`jsx-no-useless-fragment`): Ignore empty React fragments
Empty React fragments might be conditionally returned. As a result, it makes sense not to consider those as redundant and avoid reporting them.

### PR DESCRIPTION
**Pull request by yassin-kammoun-sonarsource**
Fixes #4192

### CODE REVIEW

File: packages/jsts/src/rules/S6749/decorator.ts [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+  };
+  return interceptReport(rule, (context, descriptor) => {
+    const { messageId, node, ...rest } = descriptor as any;
+
+    /* Ignore empty fragments */
+    if (node.type === 'JSXFragment' && node.children.length === 0) {
+      return;
+    }
+
+    context.report({ messageId, node, ...rest });
```
Comment (alexander-kamushkin-sonarsource) [inline packages/jsts/src/rules/S6749/decorator.ts:44]: Looks like you are not changing anything in the descriptor, should it be `context.report(descriptor);` ?

**Review by alexander-kamushkin-sonarsource — APPROVED** [review]

File: packages/jsts/src/rules/S6749/decorator.ts (hunk 1 above)
Comment (yassin-kammoun-sonarsource) [reply packages/jsts/src/rules/S6749/decorator.ts:44]: Indeed 👍
