### PR TITLE
Cherry-pick S3735 from Sonar Way Recommended into Sonar Way

### LINKED ISSUE #2526: Cherry-pick S3735 from Sonar Way Recommended into Sonar Way
- [ ] Add exception to [immediately invoked-function expressions](https://docs.google.com/spreadsheets/d/1yye3xZ1yfIjN9_LrqngXWdEkCjnRPwYMf-Nkx9kfa5w/edit#gid=0&range=P47)
- [ ] Document added exception in [RSPEC-3735](https://jira.sonarsource.com/browse/RSPEC-3735)
- [ ] Update RSPEC-based files
- [ ] Enable rule in Sonar Way Quality Profile

### PR DESCRIPTION
**Pull request by yassin-kammoun-sonarsource**
Fixes #2526

### CODE REVIEW

File: eslint-bridge/src/rules/void-use.ts [hunk 1]
```diff
@@ -36,6 +36,17 @@ export const rule: Rule.RuleModule = {
       });
     }
 
+    function isVoid0(expr: estree.UnaryExpression) {
+      return expr.argument.type === 'Literal' && 0 === expr.argument.value;
+    }
+
+    function isIIFE(expr: estree.UnaryExpression) {
```
Comment (andrea-guarino-sonarsource) [inline eslint-bridge/src/rules/void-use.ts:43]: I don't fully understand why we want to exclude IIFE from this rule, is there an FP documented somewhere?

File: eslint-bridge/tests/rules/void-use.test.ts [hunk 2]
```diff
@@ -41,23 +41,14 @@ const testCases = {
             void (0);
             `,
     },
-  ],
-  invalid: [
     {
       code: `
```
Comment (andrea-guarino-sonarsource) [inline eslint-bridge/tests/rules/void-use.test.ts:45]: Should we also exclude arrow functions?

```
void (() => 42) () 
```

File: eslint-bridge/src/rules/void-use.ts (hunk 1 above)
Comment (yassin-kammoun-sonarsource) [reply eslint-bridge/src/rules/void-use.ts:43]: Yes, it is documented in the [shared spreadsheet](https://docs.google.com/spreadsheets/d/1yye3xZ1yfIjN9_LrqngXWdEkCjnRPwYMf-Nkx9kfa5w/edit#gid=0&range=P47) prepared by Nicolas. All "cherry-picking" tickets were created based on this document.

File: eslint-bridge/tests/rules/void-use.test.ts (hunk 2 above)
Comment (yassin-kammoun-sonarsource) [reply eslint-bridge/tests/rules/void-use.test.ts:45]: That would makes sense.

File: eslint-bridge/src/rules/void-use.ts (hunk 1 above)
Comment (andrea-guarino-sonarsource) [reply eslint-bridge/src/rules/void-use.ts:43]: Can we document this FP a bit better in #2526? In the future, I don't think it will be easy to find out this comes from a spreadsheet

**Review by andrea-guarino-sonarsource — APPROVED** [review]
LGTM
