### PR TITLE
Fix SSF-181

### LINKED ISSUE #2678: Fix SSF-181
https://jira.sonarsource.com/browse/SSF-181 (not available publicly)

### PR DESCRIPTION
**Pull request by saberduck**
Fixes #2678

### CODE REVIEW

File: nodejs-utils/src/main/java/org/sonarsource/nodejs/NodeCommandBuilderImpl.java [hunk 1]
```diff
@@ -186,9 +188,9 @@ private String getVersion(String nodeExecutable) throws NodeCommandException {
   }
 
   private String retrieveNodeExecutableFromConfig(@Nullable Configuration configuration) throws NodeCommandException, IOException {
-    if (configuration != null && (configuration.hasKey(NODE_EXECUTABLE_PROPERTY) || configuration.hasKey(NODE_EXECUTABLE_PROPERTY_TS))) {
```
Comment (saberduck) [inline nodejs-utils/src/main/java/org/sonarsource/nodejs/NodeCommandBuilderImpl.java:189]: this change is not related to the PR, I just needed it to improve coverage

**Review by yassin-kammoun-sonarsource — APPROVED** [review]
LGTM! Let's wait for a green master before merging.
