### PR TITLE
Fix 'RULE' metric type for performance monitoring

### LINKED ISSUE #3341: Fix 'RULE' metric type for performance monitoring
For some reason (refactoring in the analyzer or change in ESLint?) since recently (in the middle of 9.6 cycle?) 'RULE' metric type is not provided anymore.

### PR DESCRIPTION
**Pull request by vilchik-elena**
Fixes #3341

### CODE REVIEW

**Comment by vilchik-elena** [comment]
One condition is not covered but I think it's not worthy to make it covered

File: its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/TypeScriptRuleTest.java [hunk 1]
```diff
@@ -92,10 +93,23 @@ void test() throws Exception {
       .setProperty("sonar.lits.dump.old", FileLocation.of("target/expected/ts/" + PROJECT_KEY).getFile().getAbsolutePath())
       .setProperty("sonar.lits.dump.new", FileLocation.of("target/actual/ts/" + PROJECT_KEY).getFile().getAbsolutePath())
       .setProperty("sonar.lits.differences", FileLocation.of("target/differences").getFile().getAbsolutePath())
+      .setProperty("sonar.javascript.monitoring", "true")
+      .setProperty("sonar.javascript.monitoring.path", FileLocation.of(perfMonitoringDir).getFile().getAbsolutePath())
```
Comment (saberduck) [inline its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/TypeScriptRuleTest.java:97]: I prefer to use Java's API instead of orchestrator `FileLocation` , you can use `Path.of(...).toAbsolutePath` (I think the `FileLocation` usage was copy&pasted from other analyzers, and we should stop this bad habit :)

File: its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/TypeScriptRuleTest.java [hunk 2]
```diff
@@ -92,10 +93,23 @@ void test() throws Exception {
...
       .setProperty("sonar.cpd.exclusions", "**/*");
 
     orchestrator.executeBuild(build);
 
     assertThat(new String(Files.readAllBytes(Paths.get("target/differences")), StandardCharsets.UTF_8)).isEmpty();
+    assertPerfMonitoringAvailable(perfMonitoringDir);
+  }
+
+  // asserting perf monitoring on TypeScript project as it creates all kinds of metrics
+  private void assertPerfMonitoringAvailable(String perfMonitoringDir) throws IOException {
```
Comment (saberduck) [inline its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/TypeScriptRuleTest.java:107]: better to have `Path` as argument type

File: sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImpl.java [hunk 3]
```diff
@@ -461,7 +463,7 @@ static class MonitoringOutputConsumer implements Consumer<String> {
 
     @Override
     public void accept(String s) {
-      if (HEADER.equals(s)) {
+      if (s.startsWith(HEADER_HEAD) && s.endsWith(HEADER_TAIL)) {
```
Comment (saberduck) [inline sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImpl.java:466]: wdyt about using regex here? seems like we could just have `Rule .+Time (ms) | Relative`

**Review by saberduck — CHANGES_REQUESTED** [review]
some minor comments

File: sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImpl.java (hunk 3 above)
Comment (vilchik-elena) [reply sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImpl.java:466]: I try to avoid using regex when it's possible :) but let me try)

**Review by saberduck — APPROVED** [review]
