### PR TITLE
Fix default value of JavaScript execution environments

### LINKED ISSUE #2632: Remove spaces from the default value of JavaScript execution environments
Reported in https://discuss.sonarsource.com/t/javascript-execution-environments-section-1-space-prefix/6611.

### PR DESCRIPTION
**Pull request by yassin-kammoun-sonarsource**
Fixes #2632

### CODE REVIEW

File: sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptPlugin.java [hunk 1]
```diff
@@ -73,8 +73,8 @@ public class JavaScriptPlugin implements Plugin {
   public static final String LCOV_REPORT_PATHS_DEFAULT_VALUE = "";
 
   public static final String ENVIRONMENTS = "sonar.javascript.environments";
-  public static final String ENVIRONMENTS_DEFAULT_VALUE = "amd, applescript, atomtest, browser, commonjs, couch, embertest, flow, greasemonkey, jasmine, jest, jquery, " +
-    "meteor, mocha, mongo, nashorn, node, phantomjs, prototypejs, protractor, qunit, rhino, serviceworker, shared-node-browser, shelljs, webextensions, worker, wsh, yui";
+  public static final String ENVIRONMENTS_DEFAULT_VALUE = "amd,applescript,atomtest,browser,commonjs,couch,embertest,flow,greasemonkey,jasmine,jest,jquery," +
+    "meteor,mocha,mongo,nashorn,node,phantomjs,prototypejs,protractor,qunit,rhino,serviceworker,shared-node-browser,shelljs,webextensions,worker,wsh,yui";
```
Comment (saberduck) [inline sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptPlugin.java:77]:
```suggestion
  public static final String ENVIRONMENTS_DEFAULT_VALUE = String.join(",", "amd","applescript","atomtest","browser","commonjs","couch","embertest","flow","greasemonkey","jasmine","jest","jquery",      "meteor","mocha","mongo","nashorn","node","phantomjs","prototypejs","protractor","qunit","rhino","serviceworker","shared-node-browser","shelljs","webextensions","worker","wsh","yui");
```

I think this would be less error prone in the long-term

Comment (yassin-kammoun-sonarsource) [reply sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptPlugin.java:77]: Much better indeed, thanks!
