### PR TITLE
Fix FP S1186 ('no-empty-function'): Ignore private constructors

### LINKED ISSUE #3115: Fix FP S1186 ('no-empty-function'): Ignore private constructors
https://community.sonarsource.com/t/typescript-s1186-should-not-apply-to-private-constructors/61121

### PR DESCRIPTION
**Pull request by yassin-kammoun-sonarsource**
Fixes #3115

### CODE REVIEW

File: javascript-checks/src/main/java/org/sonar/javascript/checks/EmptyFunctionCheck.java [hunk 1]
```diff
@@ -33,4 +35,13 @@ public class EmptyFunctionCheck implements EslintBasedCheck {
   public String eslintKey() {
     return "no-empty-function";
   }
+
+  @Override
+  public List<Object> configurations() {
+    return Collections.singletonList(new Config());
```
Comment (saberduck) [inline javascript-checks/src/main/java/org/sonar/javascript/checks/EmptyFunctionCheck.java:41]: I find Java 11's `List.of()` a bit more succinct (next time, no need to update this PR)

**Review by saberduck — APPROVED** [review]

File: javascript-checks/src/main/java/org/sonar/javascript/checks/EmptyFunctionCheck.java (hunk 1 above)
Comment (yassin-kammoun-sonarsource) [reply javascript-checks/src/main/java/org/sonar/javascript/checks/EmptyFunctionCheck.java:41]: I will keep that in mind for next time, thanks.
