### PR TITLE
Fix parsing error: attributes in 'script' tag in 'vue' file

### LINKED ISSUE #843: Parsing error: attributes in 'script' tag in 'vue' file
I installed the SonarJS into SonarQube, and scanned a Vue project, the result snippet as below: 
**Maybe this is a bug.**
**SonarJS version:**  3.3.0.5702 <br>
**SonarQube version:** 5.6.6<br>
"dependencies": {
             "lodash": "4.17.4",
             "vue": "2.3.4",
             "vue-resource": "1.3.4",
             "vue-router": "2.6.0",
             "vuex": "2.3.1",
             "vue-loader": "11.3.4",
             "vue-style-loader": "2.0.5",
             "vue-template-compiler": "2.3.4",
             "webpack": "^2.2.1",
             "webpack-bundle-analyzer": "^2.2.1",
             "webpack-dev-middleware": "^1.10.0",
             "webpack-hot-middleware": "^2.16.1",
             "webpack-merge": "^2.6.1"
  }

ERROR: Unable to parse file: /data/jenkins/workspace/develop/vueportal/lib/components/picker/src/picker-slot.vue
ERROR: Parse error at line 111 column 1:

101:     overflow: visible
102:   }
103: 
104:   .picker-3d .picker-item {
105:     transform-origin: center center;
106:     backface-visibility: hidden;
107:     transition-timing-function: ease-out
108:   }
109: </style>
110: 
111: <script type="text/babel">
     ^
112:   import draggable from './draggable'
113:   import translateUtil from './translate'
114:   import { once, addClass, removeClass } from './dom'
115:   import emitter from './emitter'
116:   import Vue from 'vue'
117:   if (!Vue.prototype.$isServer) {
118:     require('raf.js')
119:   }
120: 
121:   var rotateElement = function (element, angle) {.....other code}
</script>

It seems that SonarJS cannot recognize the <script> tag.

### PR DESCRIPTION
**Pull request by vilchik-elena**
Fixes #843

### CODE REVIEW

File: javascript-frontend/src/main/java/org/sonar/javascript/parser/TreeFactory.java [hunk 1]
```diff
@@ -2173,6 +2177,10 @@ private DotAccessTail(SyntaxToken dot, IdentifierTree identifierTree) {
     }
   }
 
+  static class VueScriptTag {
```
Comment (SonarTech) [inline javascript-frontend/src/main/java/org/sonar/javascript/parser/TreeFactory.java]: MINOR Remove this empty class, write its code or make it an "interface". [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=squid%3AS2094)

File: javascript-frontend/src/main/java/org/sonar/javascript/parser/TreeFactory.java [hunk 2]
```diff
@@ -2118,6 +2118,10 @@ public FlowImplementsClauseTree flowImplementsClause(InternalSyntaxToken impleme
     return new FlowImplementsClauseTreeImpl(implementsToken, parameterList(first, rest));
   }
 
+  public VueScriptTag vueScriptTag(InternalSyntaxToken token, Optional<List<JsxAttributeTree>> optional, InternalSyntaxToken token1) {
```
Comment (SonarTech) [inline javascript-frontend/src/main/java/org/sonar/javascript/parser/TreeFactory.java]: MAJOR Remove these unused method parameters. [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=squid%3AS1172)

**Comment by SonarTech** [comment]
SonarQube analysis reported 2 issues
* ![MAJOR][MAJOR] 1 major
* ![MINOR][MINOR] 1 minor

Watch the comments in this conversation to review them.

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'
