### PR TITLE
Fix FP S3827 (`no-reference-error`): Ignore Vue3 compiler macros

### LINKED ISSUE #3780: Fix FP S3827 (`no-reference-error`): Ignore Vue3 `defineProps()`, `defineEmits()` and `defineExpose()`
When using Vue3 with JavaScript, in a `<script setup>` section, Vue provides compiler macros to configure the component: `defineProps()`, `defineEmits()`, and `defineExpose()`.
Rule S3827 should check the AST to ignore these functions if they are inside a Vue file (that's to say, inside a `VElement` with a `VStartTag` having a `VAttribute` named `setup`)

Reported in https://community.sonarsource.com/t/on-the-vue3-project-defineprops-and-defineemits-should-be-automatically-available-in-script-setup/84965

### PR DESCRIPTION
**Pull request by alexander-kamushkin-sonarsource**
Fixes #3780

### CODE REVIEW

File: packages/jsts/src/rules/S3827/rule.ts [hunk 1]
```diff
@@ -83,3 +97,31 @@ function hasTypeOfOperator(node: TSESTree.Node) {
   const parent = node.parent;
   return parent?.type === 'UnaryExpression' && parent.operator === 'typeof';
 }
+
+function isVueMacro(identifier: TSESTree.Identifier, block: AST.ESLintProgram) {
```
Comment (yassin-kammoun-sonarsource) [inline packages/jsts/src/rules/S3827/rule.ts:101]: FYI

```typescript
const services = context.parserServices;
const fragment = services.getDocumentFragment();
const script = fragment.children.find(child => child.type === 'VElement' && child.name === 'script');
```

**Review by yassin-kammoun-sonarsource — APPROVED** [review]

File: packages/jsts/src/rules/S3827/rule.ts (hunk 1 above)
Comment (alexander-kamushkin-sonarsource) [reply packages/jsts/src/rules/S3827/rule.ts]: Moved `isInsideVueSetupScript` to helpers because it is also needed in S1128 (#4047)

**Review by yassin-kammoun-sonarsource — APPROVED** [review]
Thanks for extracting the helper function. LGTM!
