### PR TITLE
S6323: Add exception when empty alternation is used to make group optional

### LINKED ISSUE #2728: Add exception to S6323 about optional group

### PR DESCRIPTION
**Pull request by saberduck**
Fixes #2728

### CODE REVIEW

**Comment by saberduck** [comment]
See also https://github.com/SonarSource/rspec/pull/239

File: eslint-bridge/src/rules/no-empty-alternatives.ts [hunk 1]
```diff
@@ -40,6 +41,15 @@ export const rule: Rule.RuleModule = createRegExpRule(context => {
         });
       }
     }
+
+    function isLastEmptyInGroup(alt: regexpp.AST.Alternative) {
```
Comment (vilchik-elena) [inline eslint-bridge/src/rules/no-empty-alternatives.ts:45]: I am not fan of nested functions (it's level 3)

**Review by vilchik-elena — APPROVED** [review]
