### PR TITLE
Add quick fix for S3696 ('no-throw-literal')

### LINKED ISSUE #3017: Add quick fix for S3696: Literals should not be thrown
ESLint rule. Only for string literals and concatenation.

### PR DESCRIPTION
**Pull request by yassin-kammoun-sonarsource**
Fixes #3017

### CODE REVIEW

File: eslint-bridge/src/rules/decorators/no-throw-literal-decorator.ts [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+  rule.meta!.hasSuggestions = true;
+  return interceptReport(rule, (context, reportDescriptor) => {
+    const suggest: Rule.SuggestionReportDescriptor[] = [];
+    if ('node' in reportDescriptor) {
+      const { argument: thrown } = reportDescriptor.node as estree.ThrowStatement;
+      if (isStringLike(thrown)) {
+        const thrownText = context.getSourceCode().getText(thrown);
+        suggest.push({
+          desc: 'Throw an error object',
+          fix: fixer => fixer.replaceText(thrown, `new Error(${thrownText})`),
```
Comment (vilchik-elena) [inline eslint-bridge/src/rules/decorators/no-throw-literal-decorator.ts:37]: I wonder if it's more reliable to use `insertTextAfter` and `insertTextBefore` instead of `context.getSourceCode().getText()`. WDYT?

Comment (yassin-kammoun-sonarsource) [reply eslint-bridge/src/rules/decorators/no-throw-literal-decorator.ts:37]: Hard to say... I propose we keep it like this for now. If we manage to break the fix during validation, depending on the problem, we can then try those methods.
