### PR TITLE
Do not fail silently

### LINKED ISSUE #4437: Fail fast in most cases
Avoid unnoticed errors and green quality gates when JS analyzer crashes

https://sonarsource.atlassian.net/browse/MMF-2928

### PR DESCRIPTION
**Pull request by vdiez**
Fixes #4437

### CODE REVIEW

File: sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/bridge/AbstractBridgeSensor.java [hunk 1]
```diff
@@ -85,29 +85,38 @@ public void execute(SensorContext context) {
...
       analysisWarnings.addUnique(
-        "JavaScript/TypeScript/CSS rules were not executed. " + e.getMessage()
+        "Error while running Node.js. A supported version of Node.js is required for running the analysis for " +
+        lang +
+        " files. Please make sure a supported version of Node.js is available in the PATH. Alternatively, you can exclude " +
+        lang +
+        " files from your analysis using the 'sonar.exclusions' configuration property. " +
+        "See the docs for configuring the analysis environment: https://docs.sonarsource.com/"
+      );
+      throw new IllegalStateException(
```
Comment (saberduck) [inline sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/bridge/AbstractBridgeSensor.java:97]: I am just thinking - if we make the sensor fail here, analysis is interrupted and nothing will be posted to the SonarQube, so there will be no analysis warning, because there is no analysis. Then the above message can be just logged using the logger

File: sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/bridge/CssRuleSensorTest.java [hunk 2]
```diff
@@ -277,29 +277,18 @@ void test_no_file_to_analyze() {
...
-
   @Test
   void failed_server_should_log_error_with_css() throws IOException {
     doThrow(new NodeCommandException("Exception Message"))
       .when(bridgeServerMock)
       .startServerLazily(any());
     addInputFile("file.css");
 
-    sensor.execute(context);
-    assertThat(logTester.logs(LoggerLevel.ERROR)).contains("Exception Message");
```
Comment (ilia-kebets-sonarsource) [inline sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/bridge/CssRuleSensorTest.java:302]: we still log, don't we?

File: sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/bridge/CssRuleSensorTest.java [hunk 3]
```diff
@@ -364,7 +353,7 @@ void should_not_send_file_content_if_encoding_is_utf8_and_context_is_not_sonarli
     DefaultInputFile inputFile = new TestInputFileBuilder("moduleKey", filePath)
       .setLanguage(CssLanguage.KEY)
       .setCharset(StandardCharsets.UTF_8)
-      .setContents("css content")
+      .setContents("css content\nline 2")
```
Comment (ilia-kebets-sonarsource) [inline sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/bridge/CssRuleSensorTest.java:356]: why this change?

File: sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/bridge/CssRuleSensorTest.java [hunk 4]
```diff
@@ -277,29 +277,18 @@ void test_no_file_to_analyze() {
...
       .when(bridgeServerMock)
       .startServerLazily(any());
     addInputFile("file.css");
 
-    sensor.execute(context);
-    assertThat(logTester.logs(LoggerLevel.ERROR)).contains("Exception Message");
+    assertThatThrownBy(() -> sensor.execute(context))
+      .isInstanceOf(IllegalStateException.class)
+      .hasMessage(
+        "Error while running Node.js. A supported version of Node.js is required for running the analysis of CSS files. Please make sure a supported version of Node.js is available in the PATH. Alternatively, you can exclude CSS files from your analysis using the 'sonar.exclusions' configuration property. See the docs for configuring the analysis environment: https://docs.sonarsource.com/sonarqube/latest/analyzing-source-code/languages/javascript-typescript-css/"
```
Comment (ilia-kebets-sonarsource) [inline sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/bridge/CssRuleSensorTest.java:290]: would it be worth it to extract this message in some static function in `AbstractBridgeSensor`, or is it overkill?

File: sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/bridge/JsTsSensorTest.java [hunk 5]
```diff
@@ -172,14 +172,15 @@ void should_have_descriptor() throws Exception {
...
     JsTsSensor sensor = createSensor();
     DefaultInputFile inputFile = createInputFile(context);
-    createVueInputFile();
     createTsConfigFile();
 
+    AnalysisResponse expectedResponse = createResponse();
+    when(bridgeServerMock.analyzeTypeScript(any())).thenReturn(expectedResponse);
+    var tsProgram = new TsProgram("1", List.of(inputFile.absolutePath()), List.of());
+    when(bridgeServerMock.createProgram(any())).thenReturn(tsProgram);
+
```
Comment (ilia-kebets-sonarsource) [inline sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/bridge/JsTsSensorTest.java:183]: thanks for fixing this

File: sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/bridge/JsTsSensorTest.java [hunk 6]
```diff
@@ -902,7 +903,7 @@ private void createVueInputFile(SensorContextTester context) {
     )
       .setLanguage("js")
       .setCharset(StandardCharsets.UTF_8)
-      .setContents("<script lang=\"ts\"></script>")
+      .setContents("<script lang=\"ts\">\nif (cond)\ndoFoo(); \nelse \ndoFoo();\n</script>")
```
[the remark this answers is not in the document]
Comment (ilia-kebets-sonarsource) [reply sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/bridge/JsTsSensorTest.java:906]: as discussed, we will leave this.
