### PR TITLE
Modify rule S107: Do not count TypeScript parameter properties

### LINKED ISSUE #4014: Fix FP S107: Do not count TypeScript parameter properties
Currently, we have an exception for constructors with only parameter properties, but if we provide a few parameters among those and the total amount exceeds the limit, it gets flagged. We decide to extend the exception: when mixing both parameter properties and parameters, only count the parameters against the limit.

Issue raised in https://community.sonarsource.com/t/about-typescript-s107-dependency-injection-and-non-property-parameters/95186

### PR DESCRIPTION
**Pull request by yassin-kammoun-sonarsource**
Fixes #4014

### CODE REVIEW

**Review by ilia-kebets-sonarsource — APPROVED** [review]
Small change, otherwise LGTM!

File: packages/jsts/src/rules/S107/rule.ts [hunk 1]
```diff
@@ -45,6 +45,7 @@ export const rule: Rule.RuleModule = {
     const ruleDecoration: Rule.RuleModule = interceptReport(
       eslintMaxParams,
       function (context: Rule.RuleContext, descriptor: Rule.ReportDescriptor) {
+        const maxParams = context.options[0] as number;
```
Comment (ilia-kebets-sonarsource) [inline packages/jsts/src/rules/S107/rule.ts:48]: Can you remove the duplicate value at line 122?
