### PR TITLE
Fix FP S4328: Ignore `node:` imports

### LINKED ISSUE #3334: Fix FP S4328: Ignore `node:` imports
Rule S4328 gives a FP when using [`node:`  imports](https://nodejs.org/api/esm.html#node-imports)

### PR DESCRIPTION
**Pull request by yassin-kammoun-sonarsource**
Fixes #3334

### CODE REVIEW

File: eslint-bridge/src/linting/eslint/rules/no-implicit-dependencies.ts [hunk 1]
```diff
@@ -117,6 +117,10 @@ function raiseOnImplicitImport(
     return;
   }
 
+  if (moduleName.startsWith('node:')) {
```
Comment (ilia-kebets-sonarsource) [inline eslint-bridge/src/linting/eslint/rules/no-implicit-dependencies.ts:120]: early returns 👍

**Review by ilia-kebets-sonarsource — APPROVED** [review]
LGTM
