### PR TITLE
Rule S5332: Using clear-text protocols is security-sensitive

### LINKED ISSUE #2373: Add rule S5332 for JS/TS
## Rule S5332: Using clear-text protocols is security-sensitive

[S5332](https://jira.sonarsource.com/browse/RSPEC-5332), part of [MMF-2154](https://jira.sonarsource.com/browse/MMF-2154).

### Url scheme in string literal

Highlight literal strings that start with:
* `http://`
* `ftp://`
* `telnet://`

Matching is case insensitive.
Exception: the url domain component is a loopback address.

#### Sensitive Code Example
```
url = "http://"; // Noncompliant
url = "http://exemple.com"; // Noncompliant
url = "http://0001::1"; // Noncompliant
url = "http://dead:beef::1"; // Noncompliant
url = "http://::dead:beef:1"; // Noncompliant
url = "http://192.168.0.1"; // Noncompliant
url = "http://10.1.1.123"; // Noncompliant
url = "http://subdomain.exemple.com"; // Noncompliant

url = "ftp://"; // Noncompliant
url = "ftp://anonymous@exemple.com"; // Noncompliant
url = "telnet://"; // Noncompliant
url = "telnet://anonymous@exemple.com"; // Noncompliant
```

#### Compliant Solution
```
// Non sensitive url scheme
url = "https://"; // Compliant
url = "sftp://"; // Compliant
url = "ftps://"; // Compliant
url = "scp://"; // Compliant
url = "ssh://"; // Compliant

// Only report string staring with the sensitive url scheme
doc = "See http://exemple.com"; // Compliant
doc = "See ftp://exemple.com"; // Compliant
doc = "See telnet://exemple.com"; // Compliant

// The url domain component is a loopback address.
url = "http://localhost"; // Compliant
url = "http://127.0.0.1"; // Compliant
url = "http://::1"; // Compliant
url = "ftp://user@localhost"; // Compliant
```

### ftp

Report `Client.connect()` calls of the `ftp` module if the `secure` attribute is `undefined` or `false`.

#### Sensitive Code Example
```
var Client = require('ftp');
var c = new Client();
c.connect({
  'secure': false // Sensitive
});
```

#### Compliant Solution
```
var Client = require('ftp');
var c = new Client();
c.connect({
  'secure': true // Compliant
});
```

### telnet-client

Report loading of the `telnet-client` module. There is no compliant solution.

#### Sensitive Code Example
```
const Telnet = require('telnet-client'); // Sensitive
```

### nodemailer

Report `createTransport()` calls of the `nodemailer` module if none if this conditions is met:

 * `secure` is `true`
 * `requireTLS` is `true`
 * `port` is 465 and `secure` is not `false`

#### Sensitive Code Example
```
const nodemailer = require("nodemailer");

let transporter = nodemailer.createTransport({ // Sensitive
  secure: false,
  requireTLS: false,
  port: 1234
});
```

#### Compliant Solution
```
const nodemailer = require("nodemailer");

let transporter = nodemailer.createTransport({
  secure: true, // Compliant
});
```

```
const nodemailer = require("nodemailer");

let transporter = nodemailer.createTransport({
  requireTLS: true, // Compliant
});
```

```
const nodemailer = require("nodemailer");

let transporter = nodemailer.createTransport({
  port: 465, // Compliant (port 465 enables encryption automatically)
});
```

### PR DESCRIPTION
**Pull request by guillaume-dequenne-sonarsource**
Fixes #2373 
Please don't merge before custom rules API change is reverted.

### CODE REVIEW

File: eslint-bridge/src/rules/no-clear-text-protocols.ts [hunk 1]
```diff
@@ -0,0 +1,158 @@
...
+      const secure = getObjectExpressionProperty(firstArgValue, 'secure');
+      const requireTls = getObjectExpressionProperty(firstArgValue, 'requireTLS');
+      const port = getObjectExpressionProperty(firstArgValue, 'port');
+      if (secure && secure.value.type === 'Literal') {
+        if (secure.value.raw === 'false') {
+          context.report({ node: callExpression, message: getMessage('http') });
+        }
+        return;
+      }
+      if (requireTls && requireTls.value.type === 'Literal' && requireTls.value.raw === 'true') {
```
Comment (andrea-guarino-sonarsource) [inline eslint-bridge/src/rules/no-clear-text-protocols.ts:50]: I think we shouldn't report if we're not sure about the value of the expression we 'resolved'.
For example:
```javascript
      const nodemailer = require("nodemailer");

      let transporter = nodemailer.createTransport({ // OK
        secure: false,
        requireTLS: someGlobalVar,
        port: 1234
      });
```

File: eslint-bridge/src/rules/no-clear-text-protocols.ts [hunk 2]
```diff
@@ -0,0 +1,158 @@
...
+        }
+      }
+    }
+
+    return {
+      Literal: (node: estree.Node) => {
+        const literal = node as estree.Literal;
+        const value = literal.value;
+        if (typeof value === 'string' && !value.match(LOOPBACK_PATTERN)) {
+          const insecure = INSECURE_PROTOCOLS.find(i => value.startsWith(`${i}://`));
```
Comment (andrea-guarino-sonarsource) [inline eslint-bridge/src/rules/no-clear-text-protocols.ts:112]: I think we could try to be more precise, i.e. let's try to parse the full string as http / ftp / telnet URL instead of just checking the prefix of the string literal . wdyt?

File: eslint-bridge/src/rules/no-clear-text-protocols.ts (hunk 1 above)
Comment (guillaume-dequenne-sonarsource) [reply eslint-bridge/src/rules/no-clear-text-protocols.ts:50]: Makes sense! Thanks!

File: eslint-bridge/src/rules/no-clear-text-protocols.ts (hunk 2 above)
Comment (guillaume-dequenne-sonarsource) [reply eslint-bridge/src/rules/no-clear-text-protocols.ts:112]: Indeed that's actually what we do in other languages. Thanks!

**Review by andrea-guarino-sonarsource — APPROVED** [review]
LGTM
