### PR TITLE
Fix FP S6442 (`no-hook-setter-in-body`): Shouldn't raise when used conditionally

### LINKED ISSUE #3516: Fix FP in S6442 improve corner case and fix rule title
| Label | Description |
| --- | --- |
|Rule | S6442 "React's useState used directly in render function" |
| Reproduce | False positive on some edge cases where a derived state is intended. |

## Explanation

As[ pointed out](https://twitter.com/gigonake/status/1584901827165884418?s=20&t=GDxDIFW7PbZQCUXEM7-I7A) by a user, there are some [corner cases](https://beta.reactjs.org/apis/react/useState#storing-information-from-previous-renders) where you might legitimately want to call the state setter in the render, although inside a condition to avoid the infinite loop.

React discourages this pattern ("This pattern can be hard to understand and is usually best avoided"), but I guess it is a false positive nonetheless.

## Suggestion

I suggest we ignore cases where the state setter is inside a conditional.
For example:

```js
    const [language, setLanguage] = useState("fr-FR");

    if (enjoySharpKnives) {
        setLanguage(navigator.language);
    }
```

Perhaps we can go all the way and require an explicit return statement since this is what React is fundamentally doing internally.

```js
    if (enjoySharpKnives) {
        setLanguage(navigator.language);
        return null;
    }
```

## Corrections

The title of the rule says the opposite of what we want:
```diff
- React's useState hook should only be used in the render function or body of a component
+ React's useState hook should not be used directly in the render function or body of a component
```

While we are there, there are also extra semicolons in the code examples:
```diff
function ShowLanguage() {
    ...
-};
+}
```

### PR DESCRIPTION
**Pull request by saberduck**
Fixes #3516

### CODE REVIEW

File: eslint-bridge/src/linting/eslint/rules/no-hook-setter-in-body.ts [hunk 1]
```diff
@@ -80,6 +82,13 @@ export const rule: Rule.RuleModule = {
       return scope !== null && searchUpperFunctionScope(context.getScope()) === scope;
     }
 
+    function isConditional(node: estree.Node): boolean {
```
Comment (ilia-kebets-sonarsource) [inline eslint-bridge/src/linting/eslint/rules/no-hook-setter-in-body.ts:85]:
```suggestion
    function isInsideConditional(node: estree.Node): boolean {
```

File: eslint-bridge/src/linting/eslint/rules/no-hook-setter-in-body.ts [hunk 2]
```diff
@@ -117,7 +126,11 @@ export const rule: Rule.RuleModule = {
 
       // Selector matching function calls like: setCount(1)
       'CallExpression[callee.type="Identifier"][arguments.length=1]'(node: estree.CallExpression) {
-        if (!isInsideFunctionScope(reactComponentScope) || setters.length === 0) {
+        if (
+          !isInsideFunctionScope(reactComponentScope) ||
+          setters.length === 0 ||
+          isConditional(node)
```
Comment (ilia-kebets-sonarsource) [inline eslint-bridge/src/linting/eslint/rules/no-hook-setter-in-body.ts:132]:
```suggestion
          isInsideConditional(node)
```

**Comment by ilia-kebets-sonarsource** [comment]
I proposed a small function refactor.

Should you also apply the RSPEC change that Gab mentioned in corrections in https://github.com/SonarSource/SonarJS/issues/3516?

**Review by ilia-kebets-sonarsource — APPROVED** [review]
Apart from my comments, LGTM.

I Fixed the PR title to reflect https://xtranet-sonarsource.atlassian.net/wiki/spaces/LANG/pages/2567241836/Commit+and+Tickets+Guidelines
