### PR TITLE
Do not try to restart Node process if it's not answering

### LINKED ISSUE #2616: EslintBridgeServer should handle unresponsive node process in SonarLint context
Sometimes `eslint-bridge` node process might get stuck. SonarLint might still continue to attempt to run the analysis and we are not able to recover from such failure gracefully. Current implementation will again deploy the bundle and mistakenly append the command line arguments when launching the process again.

When `startServerLazily` is invoked and `isAlive()` call returns `false` we should handle two possibilties
1. we are starting the server for the first time, so we should deploy and start (this is what's done currently)
2. there is already unresponsive node process, in which case we should do cleanup or fail

(as reported by @jblievremont)
Steps to reproduce:

Open IntelliJ (or WebStorm) with SonarLint installed
Open a TS file: the ESLint bridge server starts with command:
```
/home/user/.nvm/versions/node/v14.3.0/bin/node /home/user/.cache/JetBrains/IntelliJIdea2021.1/tmp/sonarlint/.sonartmp_13219161808921726661/eslint-bridge-bundle/package/bin/server 34317 127.0.0.1 /opt/Dev/SonarSource/sonarlint-vscode true true 
```
Wait for end of analysis
Kill the node process
Close/Reopen the TS file: the ESLint bridge tries to start and times out with command:
```
/home/user/.nvm/versions/node/v14.3.0/bin/node /home/user/.cache/JetBrains/IntelliJIdea2021.1/tmp/sonarlint/.sonartmp_13219161808921726661/eslint-bridge-bundle/package/bin/server 34317 127.0.0.1 /opt/Dev/SonarSource/sonarlint-vscode true true  44885 127.0.0.1 /opt/Dev/SonarSource/sonarlint-vscode true true
```

Note that all arguments after the path to the server script are duplicated.

### PR DESCRIPTION
**Pull request by vilchik-elena**
Fixes #2616

### CODE REVIEW

File: sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImpl.java [hunk 1]
```diff
@@ -38,6 +38,7 @@
 import okhttp3.Response;
 import org.sonar.api.SonarProduct;
 import org.sonar.api.batch.sensor.SensorContext;
+import org.sonar.api.internal.google.common.annotations.VisibleForTesting;
```
Comment (saberduck) [inline sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImpl.java:41]: I don't like importing shaded artifacts from sonar-api package. Imo just replace this annotation with the comment.

**Review by saberduck — APPROVED** [review]
