### PR TITLE
Fix FP on S3798 when require is used as rhs

### LINKED ISSUE #2366: Fix FP on S3798 when require is used as rhs
S3798 should not raise issues on cases such as:

`var grunt = require('grunt');`

### PR DESCRIPTION
**Pull request by yassin-kammoun-sonarsource**
Fixes #2366

### CODE REVIEW

File: eslint-bridge/src/rules/declarations-in-global-scope.ts [hunk 1]
```diff
@@ -55,3 +56,12 @@ export const rule: Rule.RuleModule = {
 function findModuleScope(context: Rule.RuleContext) {
   return context.getSourceCode().scopeManager.scopes.find(s => s.type === 'module');
 }
+
+function isRequire(node: estree.Node | null | undefined) {
+  return (
+    node?.type === 'CallExpression' &&
+    node.arguments.length === 1 &&
+    node.callee.type === 'Identifier' &&
```
Comment (andrea-guarino-sonarsource) [inline eslint-bridge/src/rules/declarations-in-global-scope.ts:64]: **Minor:** you could use `isIdentifier(node.callee, 'require')` from `utils`

**Review by andrea-guarino-sonarsource — APPROVED** [review]
LGTM
