### PR TITLE
Fix FP S6766 (`react/no-unescaped-entities​`): Remove `'` and `"` from the list of forbidden entitiles

### LINKED ISSUE #4178: Fix FP S6766 (`react/no-unescaped-entities​`): Remove `'` and `"` from the list of forbidden entitiles
The S6766 rule raises a large number of false positives for `'` and `"` characters, which should be removed from the forbidden entities list, leaving only `>` and `}` as valid targets

### PR DESCRIPTION
**Pull request by alexander-kamushkin-sonarsource**
Fixes #4178

### CODE REVIEW

File: sonar-plugin/javascript-checks/src/main/java/org/sonar/javascript/checks/NoUnescapedEntitiesCheck.java [hunk 1]
```diff
@@ -33,4 +36,14 @@ public class NoUnescapedEntitiesCheck implements EslintBasedCheck {
...
   }
+
+  @Override
+  public List<Object> configurations() {
+    return Collections.singletonList(new Config());
+  }
+
+  private static class Config {
+
+    List<String> forbid = Arrays.asList(">", "}");
```
Comment (yassin-kammoun-sonarsource) [inline sonar-plugin/javascript-checks/src/main/java/org/sonar/javascript/checks/NoUnescapedEntitiesCheck.java:47]:
```suggestion
    List<String> forbid = List.of(">", "}");
```

File: sonar-plugin/javascript-checks/src/main/java/org/sonar/javascript/checks/NoUnescapedEntitiesCheck.java [hunk 2]
```diff
@@ -19,6 +19,9 @@
  */
 package org.sonar.javascript.checks;
 
+import java.util.Arrays;
+import java.util.Collections;
+import java.util.List;
```
Comment (yassin-kammoun-sonarsource) [inline sonar-plugin/javascript-checks/src/main/java/org/sonar/javascript/checks/NoUnescapedEntitiesCheck.java:24]:
```suggestion
import java.util.Collections;
import java.util.List;
```

**Review by yassin-kammoun-sonarsource — APPROVED** [review]
