### PR TITLE
Add quick fix for S2871 ('no-alphabetical-sort')

### LINKED ISSUE #3011: Add quick fix for S2871: A compare function should be provided when using "Array.prototype.sort()"
SonarJS rule.

### PR DESCRIPTION
**Pull request by yassin-kammoun-sonarsource**
Fixes #3011

### CODE REVIEW

File: eslint-bridge/src/rules/no-alphabetical-sort.ts [hunk 1]
```diff
@@ -25,11 +25,15 @@ import { TSESTree } from '@typescript-eslint/experimental-utils';
...
 
+const compareFunctionPlaceholder = '(a, b) => (a - b)';
+
 export const rule: Rule.RuleModule = {
   meta: {
+    hasSuggestions: true,
     messages: {
       provideCompareFunction:
         'Provide a compare function to avoid sorting elements alphabetically.',
+      suggestCompareFunction: 'Add comparator',
```
Comment (vilchik-elena) [inline eslint-bridge/src/rules/no-alphabetical-sort.ts:36]: `Add comparator function for sort in ascending order`

**Review by vilchik-elena — APPROVED** [review]
All good, I would just change the message to be more specific
