### PR TITLE
Analyze files without tsconfig also when using AnalysisWithWatchProgram

### LINKED ISSUE #3883: Regression on security benchmark
We are missing JS issues on codeql-js benchmark

### PR DESCRIPTION
**Pull request by saberduck**
- `ProjectTsConfigs` need to be initialized lazily
- Analyze files without tsconfig also when using analysis with watch program

Fixes #3883

### CODE REVIEW

File: src/services/program/program.ts [hunk 1]
```diff
@@ -58,8 +65,11 @@ const projectTSConfigs = new ProjectTSConfigs();
 export function getProgramForFile(
   input: JsTsAnalysisInput,
   cache = programCache,
-  tsconfigs = projectTSConfigs,
+  tsconfigs?: ProjectTSConfigs,
 ): ts.Program {
+  if (!tsconfigs) {
+    tsconfigs = getDefaultTSConfigs();
```
Comment (victor-diez-sonarsource) [inline src/services/program/program.ts:71]: I understand the change and I agree with it, but AFAIK this is not being used in master right? This should only apply on the new PR enabling the new codepath. We can discuss this on monday.

**Review by victor-diez-sonarsource — APPROVED** [review]

File: src/services/program/program.ts (hunk 1 above)
Comment (saberduck) [reply src/services/program/program.ts:71]: it is, because `program.ts` is imported in routing modules, so the constructor was invoked.
