### PR TITLE
Fix highlighting on S3800 for FunctionLike declarations

### LINKED ISSUE #2480: Fix highlighting on S3800 for FunctionLike declarations
Currently we highlight whole node if  node is not `FunctionDeclaration`. This can be ugly for longer function expressions used as methods. 

2021-02-09 22_17_49-Refactor this function to always return the same type

### PR DESCRIPTION
**Pull request by yassin-kammoun-sonarsource**
Fixes #2480

### CODE REVIEW

File: eslint-bridge/src/rules/function-return-type.ts [hunk 1]
```diff
@@ -87,7 +89,7 @@ export const rule: Rule.RuleModule = {
                   )}`,
               ),
             ),
-            node: node.type === 'FunctionDeclaration' && node.id ? node.id : node,
+            loc: getMainFunctionTokenLocation(node as estree.Function, getParent(context), context),
```
Comment (saberduck) [inline eslint-bridge/src/rules/function-return-type.ts:92]: I think you could use `TSESTree` types for `node` and access `.parent` field instead of this `getParent` call

Comment (yassin-kammoun-sonarsource) [reply eslint-bridge/src/rules/function-return-type.ts:92]: Type checking will fail because `getMainFunctionTokenLocation` from eslint-plugin-sonarjs expects ESTree node types, which are not compatible with TSESTree types. Unless we change the signature of the function and release a new version of the plugin, we won't be able to make the change.

File: eslint-bridge/src/rules/function-return-type.ts [hunk 2]
```diff
@@ -21,6 +21,8 @@
 
 import { TSESTree } from '@typescript-eslint/experimental-utils';
 import { Rule } from 'eslint';
+import { getMainFunctionTokenLocation } from 'eslint-plugin-sonarjs/lib/utils/locations';
```
Comment (saberduck) [inline eslint-bridge/src/rules/function-return-type.ts:24]: just a remark, probably nothing to do, it would have been better to export the function in the package, so we don't need to import such a "deep" path. Not sure how to handle this in the long term

**Review by saberduck — APPROVED** [review]
small remark to use `TSESTree.Node.parent` instead of `getParent` , otherwise lgtm
