### PR TITLE
Fix FP on S128 when 'process.exit' is called

### LINKED ISSUE #2042: FP S128 (sonar-no-fallthrough): 'process.exit' call
```
switch (x) {
  case 42: // FP
    process.exit(1);
}
```

### PR DESCRIPTION
**Pull request by guillaume-dequenne-sonarsource**
Fixes #2042

### CODE REVIEW

File: eslint-bridge/src/rules/sonar-no-fallthrough.ts [hunk 1]
```diff
@@ -27,27 +27,88 @@ import { getParent } from 'eslint-plugin-sonarjs/lib/utils/nodes';
...
+        }
+      }
+      return true;
+    }
+
     return {
       onCodePathStart(codePath: Rule.CodePath) {
         currentCodePath = codePath;
       },
       onCodePathEnd() {
```
Comment (saberduck) [inline eslint-bridge/src/rules/sonar-no-fallthrough.ts:61]: I think this can be deleted (I know it's not your change, but to simplify logic)

File: eslint-bridge/src/rules/sonar-no-fallthrough.ts [hunk 2]
```diff
@@ -27,27 +27,79 @@ import { getParent } from 'eslint-plugin-sonarjs/lib/utils/nodes';
...
+        const initialSegment: Rule.CodePathSegment = initialSegmentsBySwitchCase.get(switchCase)!;
+        const segmentsToConsider = segmentsInSwitchCase.get(switchCase);
+        let allPathsCallExit = false;
+        if (!!segmentsToConsider && segmentsWithExit.size !== 0) {
+          segmentsToConsider.add(initialSegment.id);
+          allPathsCallExit = allSegmentsReachProcessExitCall(initialSegment, segmentsToConsider);
+        }
         const { cases } = getParent(context) as estree.SwitchStatement;
         if (
           currentCodePath!.currentSegments.some(s => s.reachable) &&
```
Comment (saberduck) [inline eslint-bridge/src/rules/sonar-no-fallthrough.ts:98]: we can probably extend this condition that all reachable blocks here, which have a previous segment with `process.exit` call are also unreachable for the purpose of this rule. This should help to avoid the need of keeping track of current segments. However, we still need to be able to stop looking beyond the initial segment.

File: eslint-bridge/src/rules/sonar-no-fallthrough.ts (hunk 1 above)
Comment (guillaume-dequenne-sonarsource) [reply eslint-bridge/src/rules/sonar-no-fallthrough.ts:62]: Actually it's still required to handle nested functions in the switch cases.

**Review by saberduck — APPROVED** [review]
nice work!
