### PR TITLE
Fix FP S4158: array overridden inside nested function can be nonempty

### LINKED ISSUE #1974: FP S4158: array written inside function
```js
function foo() {
  let array = [];
  f();
  array.indexOf('x'); // FP

  function f() {
    array = h();
    // array[1] = 42; // note that when the line above is replaced by this one, FP issue disappears
  }
}
```

Also FP disappears if function `f` is declared above `array.indexOf('x')`

### PR DESCRIPTION
**Pull request by andrey-tyukin-sonarsource**
Fixes #1974

### CODE REVIEW

**Comment by andrey-tyukin-sonarsource** [comment]
The rule now completely ignores the order of usages.
The boolean state that was both mutated and read during the traversal of usages has been eliminated.
Now it reports if and only if it non-vacuously holds that for all writing usages the write must leave the collection empty, i.e.:

  * There is at least one write that definitely makes the collection empty.
  * There are no writes that might make the collection non-empty.

Note that it is not necessary to check the state of `emptyAssignmentExists` during the iteration, i.e. what ends up in the list of reported issues no longer depends on the order of usages.

File: eslint-bridge/src/rules/no-empty-collection.ts [hunk 1]
```diff
@@ -102,30 +102,42 @@ function reportEmptyCollectionUsage(variable: Scope.Variable, context: Rule.Rule
...
     if (ref.isWriteOnly()) {
-      isEmptyCollection = isReferenceAssigningEmptyCollection(ref);
-    } else {
-      if (isReadCollectionPattern(ref)) {
-        if (isEmptyCollection) {
-          usedReferences.push(ref);
-        }
-      } else {
-        // One references is a write
+      const isEmptyAssignment = isReferenceAssigningEmptyCollection(ref);
```
Comment (vilchik-elena) [inline eslint-bridge/src/rules/no-empty-collection.ts:116]: I would inline this variable

File: eslint-bridge/src/rules/no-empty-collection.ts [hunk 2]
```diff
@@ -102,30 +102,42 @@ function reportEmptyCollectionUsage(variable: Scope.Variable, context: Rule.Rule
...
+      if (!isEmptyAssignment) {
```
Comment (vilchik-elena) [inline eslint-bridge/src/rules/no-empty-collection.ts:117]: remove negation and swap the branches

File: eslint-bridge/src/rules/no-empty-collection.ts [hunk 3]
```diff
@@ -102,30 +102,42 @@ function reportEmptyCollectionUsage(variable: Scope.Variable, context: Rule.Rule
...
+        // At least one usage of the collection is nonempty.
```
Comment (vilchik-elena) [inline eslint-bridge/src/rules/no-empty-collection.ts:118]: -> `// collection is written to a non-empty array`

File: eslint-bridge/src/rules/no-empty-collection.ts [hunk 4]
```diff
@@ -102,30 +102,42 @@ function reportEmptyCollectionUsage(variable: Scope.Variable, context: Rule.Rule
     return;
   }
 
+  if (variable.defs.some(d => d.type === 'Parameter' || d.type === 'ImportBinding')) {
+    // Bound value initialized elsewhere, could be non-empty.
+    return;
+  }
+
+  // All reading usages that are meaningful only if the accessed collection can be nonempty.
   const usedReferences = [];
```
Comment (vilchik-elena) [inline eslint-bridge/src/rules/no-empty-collection.ts:111]: let's rename to `readReferences`(then may be comment can be dropped)

File: eslint-bridge/src/rules/no-empty-collection.ts [hunk 5]
```diff
@@ -102,30 +102,42 @@ function reportEmptyCollectionUsage(variable: Scope.Variable, context: Rule.Rule
...
+      return;
     }
   }
 
-  usedReferences.forEach(ref => {
-    context.report({
-      message: `Review this usage of "${ref.identifier.name}" as it can only be empty here.`,
-      node: ref.identifier,
+  if (emptyAssignmentExists) {
+    // All assignments are empty, and there exists at least one such assignment.
```
Comment (vilchik-elena) [inline eslint-bridge/src/rules/no-empty-collection.ts:133]: IMHO comments are required when logic can't be easily inferred from the code. Here I believe it's better without comment

File: eslint-bridge/src/rules/no-empty-collection.ts [hunk 6]
```diff
@@ -102,30 +102,42 @@ function reportEmptyCollectionUsage(variable: Scope.Variable, context: Rule.Rule
...
+        // At least one usage of the collection is nonempty.
+        // We ignore the order of usages, and therefore consider all reads to be safe.
         return;
+      } else {
+        emptyAssignmentExists = true;
       }
+    } else if (isReadCollectionPattern(ref)) {
+      usedReferences.push(ref);
+    } else {
+      // Some not explicitly handled construct that might make the collection non-empty.
```
Comment (vilchik-elena) [inline eslint-bridge/src/rules/no-empty-collection.ts:127]: same about comment, write it properly or better not write at all (pretty valid option :) try to make code logic and variable names as expressing as possible so that comment is not required)

if you want to keep the comment I would phase it this way: `// some unknown operation on the collection, to not produce FPs we assume it can make collection non-empty`

File: eslint-bridge/src/rules/no-empty-collection.ts [hunk 7]
```diff
@@ -159,6 +171,10 @@ function isEmptyCollectionType(node: estree.Node) {
   return false;
 }
 
+/**
+ * Checks whether this usage would be invalid if the collection turns out
```
Comment (vilchik-elena) [inline eslint-bridge/src/rules/no-empty-collection.ts:175]: better rename method if you believe the name is not expressive enough than adding this comment

File: eslint-bridge/tests/rules/no-empty-collection.test.ts [hunk 8]
```diff
@@ -168,6 +170,52 @@ ruleTester.run('Empty collections should not be accessed or iterated', rule, {
...
+        innerFunction();
+        a.indexOf('x');
+      
+        function innerFunction() {
+          a[0] = 42;
+        }
+      }`,
+    },
+    {
+      code: `function overridingInInnerFunction() {
```
Comment (vilchik-elena) [inline eslint-bridge/tests/rules/no-empty-collection.test.ts:185]: `overwriting` may be better?

File: eslint-bridge/tests/rules/no-empty-collection.test.ts [hunk 9]
```diff
@@ -168,6 +170,52 @@ ruleTester.run('Empty collections should not be accessed or iterated', rule, {
...
+        a.indexOf('x');
+      
+        function innerFunction() {
+          a = unknownFunction();
+        }
+      }`,
+    },
+    {
+      code: `
+      function parametersAreIgnoreUnlessReAsigned(parameterArray: number[]) {
```
Comment (vilchik-elena) [inline eslint-bridge/tests/rules/no-empty-collection.test.ts:197]: I believe parameters are always ignored, so name could be just `parametersAreIgnored`

File: eslint-bridge/tests/rules/no-empty-collection.test.ts [hunk 10]
```diff
@@ -168,6 +170,52 @@ ruleTester.run('Empty collections should not be accessed or iterated', rule, {
...
+        foo(parameterArray[1]);
+        parameterArray = [];
+        foo(parameterArray[1]); // FN, traded for FP in issue-1974
```
Comment (vilchik-elena) [inline eslint-bridge/tests/rules/no-empty-collection.test.ts:200]: `// FN, to avoid FPs (like in issue-1974) we ignore the order of references and so completely ignore parameters`

File: eslint-bridge/tests/rules/no-empty-collection.test.ts [hunk 11]
```diff
@@ -168,6 +170,52 @@ ruleTester.run('Empty collections should not be accessed or iterated', rule, {
...
+    },
+    {
+      code: `
+      function argumentsAreNonempty() {
+        console.log(arguments[0]);
+      }`,
+    },
+    {
+      code: `
+      function minErr() {
```
Comment (vilchik-elena) [inline eslint-bridge/tests/rules/no-empty-collection.test.ts:211]: what are we testing here?

Comment (andrey-tyukin-sonarsource) [reply eslint-bridge/tests/rules/no-empty-collection.test.ts:211]: It's a somewhat reduced code snippet that somewhat unexpectedly failed the integration tests. Removed it from unit tests - if the problem reoccurs, it will be seen in the integration tests.

File: eslint-bridge/tests/rules/no-empty-collection.test.ts (hunk 10 above)
Comment (andrey-tyukin-sonarsource) [reply eslint-bridge/tests/rules/no-empty-collection.test.ts:200]: Added something along this lines.

File: eslint-bridge/tests/rules/no-empty-collection.test.ts (hunk 8 above)
Comment (andrey-tyukin-sonarsource) [reply eslint-bridge/tests/rules/no-empty-collection.test.ts:185]: Very true. https://stackoverflow.com/questions/8651562/overwrite-or-override/8651622#comment18314356_8651622

File: eslint-bridge/src/rules/no-empty-collection.ts (hunk 7 above)
Comment (andrey-tyukin-sonarsource) [reply eslint-bridge/src/rules/no-empty-collection.ts:175]: Renamed. Retained the comment anyway, because there is no way to cram the precise formulation with all the modalities into a function name - it would be too long.

File: eslint-bridge/src/rules/no-empty-collection.ts (hunk 5 above)
Comment (andrey-tyukin-sonarsource) [reply eslint-bridge/src/rules/no-empty-collection.ts:133]: In combination with the comment in line 127, this one indeed becomes unnecessary.

File: eslint-bridge/src/rules/no-empty-collection.ts (hunk 4 above)
Comment (andrey-tyukin-sonarsource) [reply eslint-bridge/src/rules/no-empty-collection.ts:111]: I renamed the method into `isReadingCollectionUsage` and this one into `readingUsages` to keep it somewhat consistent.

File: eslint-bridge/src/rules/no-empty-collection.ts (hunk 2 above)
Comment (andrey-tyukin-sonarsource) [reply eslint-bridge/src/rules/no-empty-collection.ts:117]: Fair enough, I guess [early return](https://softwareengineering.stackexchange.com/a/18459/267303) doesn't really apply inside of loops.

File: eslint-bridge/src/rules/no-empty-collection.ts (hunk 3 above)
Comment (vilchik-elena) [reply eslint-bridge/src/rules/no-empty-collection.ts:118]: @andrey-tyukin-sonarsource not handled

File: eslint-bridge/src/rules/no-empty-collection.ts [hunk 12]
```diff
@@ -102,30 +102,40 @@ function reportEmptyCollectionUsage(variable: Scope.Variable, context: Rule.Rule
...
 
-  const usedReferences = [];
-  let isEmptyCollection = false;
+  if (variable.defs.some(d => d.type === 'Parameter' || d.type === 'ImportBinding')) {
+    // Bound value initialized elsewhere, could be non-empty.
+    return;
+  }
+
+  const readingUsages = [];
+  let assignmentOfEmptyCollectionExists = false;
```
Comment (vilchik-elena) [inline eslint-bridge/src/rules/no-empty-collection.ts:111]: imho it's better to start boolean var with `is` or `has`

File: eslint-bridge/src/rules/no-empty-collection.ts (hunk 3 above)
Comment (andrey-tyukin-sonarsource) [reply eslint-bridge/src/rules/no-empty-collection.ts:118]: I assume you meant "collection is overwritten by a non-empty array". I've added a comment that is arguably more precise than what was there previously, I think it should suffice.

File: eslint-bridge/src/rules/no-empty-collection.ts [hunk 13]
```diff
@@ -102,30 +102,42 @@ function reportEmptyCollectionUsage(variable: Scope.Variable, context: Rule.Rule
     return;
   }
 
+  if (variable.defs.some(d => d.type === 'Parameter' || d.type === 'ImportBinding')) {
```
[the remark this answers is not in the document]
Comment (andrey-tyukin-sonarsource) [reply eslint-bridge/src/rules/no-empty-collection.ts:105]: Added a test with an import from a non-existent package `nonemptyCollections` (just a hint so it's easier to search)

File: eslint-bridge/src/rules/no-empty-collection.ts (hunk 3 above)
Comment (vilchik-elena) [reply eslint-bridge/src/rules/no-empty-collection.ts:118]: @andrey-tyukin-sonarsource what do you mean? I still see the same comment. And you are right I was wrong, it should be `// something which is not empty array is assigned to the collection`
I would not use "overwrite" here, as it could be first and the only "write", so nothing to "overwrite"

File: eslint-bridge/src/rules/no-empty-collection.ts (hunk 12 above)
Comment (andrey-tyukin-sonarsource) [reply eslint-bridge/src/rules/no-empty-collection.ts:111]: Ok. I think, one can rule out the "is" in this case. The prefix `is` is almost exclusively used for predicates. For example, the predicate "mortal(Socrates)" would be expressed as "Socrates is mortal" in prose, or as `socrates.isMortal()` in code. But this here does not check a predicate, it computes a truth value of a proposition with existential quantifier `exists(collection -> isReferenceAssigningEmptyCollection(collection))`, which would be expressed in prose as "There exists an assignment of an empty collection". There is no "is" in that either. 

Regarding the `has` - I'm not sure, what would be the subject in the "x has y" relation? The code? I guess, if one agrees that one implicitly means the code here, then one could change it to `has`.

File: eslint-bridge/src/rules/no-empty-collection.ts (hunk 3 above)
Comment (andrey-tyukin-sonarsource) [reply eslint-bridge/src/rules/no-empty-collection.ts:118]: Ok, yes. It's doesn't have to be an overrite. It also doesn't necessarily have to be an array. I'd leave it at "there is at least one operation that might make the collection non-empty", if there are no objections.
