### PR TITLE
Add quick fix for S3403 ('different-types-comparison')

### LINKED ISSUE #3014: Add quick fix for S3403: Strict equality operators should not be used with dissimilar types
SonarJS rule.

### PR DESCRIPTION
**Pull request by yassin-kammoun-sonarsource**
Fixes #3014

### CODE REVIEW

File: eslint-bridge/src/rules/different-types-comparison.ts [hunk 1]
```diff
@@ -94,6 +95,17 @@ export const rule: Rule.RuleModule = {
               .getSourceCode()
               .getTokensBetween(left, right)
               .find(token => token.type === 'Punctuator' && token.value === operator)!.loc,
+            suggest: [
+              {
+                desc: `Replace "${actual}" with "${expected}"`,
+                fix: fixer => {
+                  const operatorToken = context
```
Comment (vilchik-elena) [inline eslint-bridge/src/rules/different-types-comparison.ts:102]: we compute it twice (see `loc`)

**Review by vilchik-elena — CHANGES_REQUESTED** [review]

File: eslint-bridge/src/rules/different-types-comparison.ts (hunk 1 above)
Comment (yassin-kammoun-sonarsource) [reply eslint-bridge/src/rules/different-types-comparison.ts:102]: Nice catch

**Review by vilchik-elena — APPROVED** [review]
