### PR TITLE
Fix FP ('no-try-promise'): consider yield as an alternative to await

### LINKED ISSUE #2683: Consider `yield` in S4822 (no-try-promise)
```js
function * foo() {
  try {
    yield somePromise(); // FP
  } catch (e) {
  }
}
```

`yield` is an alternative to the `await`

Reported in https://community.sonarsource.com/t/typescript-s4822-yield-keyword-should-be-accepted/26778

### PR DESCRIPTION
**Pull request by yassin-kammoun-sonarsource**
Fixes #2683

### CODE REVIEW

File: eslint-bridge/src/rules/no-try-promise.ts [hunk 1]
```diff
@@ -72,7 +72,9 @@ function visitTryStatement(
       }
 
       if (
-        (callLikeExpr.parent && callLikeExpr.parent.type === 'AwaitExpression') ||
+        (callLikeExpr.parent &&
```
Comment (vilchik-elena) [inline eslint-bridge/src/rules/no-try-promise.ts:75]: this condition was already complex:) how about extracting part of it?

File: eslint-bridge/tests/rules/no-try-promise.test.ts [hunk 2]
```diff
@@ -85,6 +85,18 @@ ruleTester.run(`Promise rejections should not be caught by 'try' block`, rule, {
       }
       `,
     },
+    {
+      code: `
+      function returningPromise() { return Promise.reject(); }
+      async function okWithYield() {
```
Comment (vilchik-elena) [inline eslint-bridge/tests/rules/no-try-promise.test.ts:91]: let's add `*` to function to be explicit that it's generator
