### PR TITLE
Fix project size calculation for JavaScript type-checking in SonarLint context

### LINKED ISSUE #4187: Fix project size calculation for JavaScript type-checking in SonarLint context
For performance reasons, the type-checking of JavaScript files in SonarLint context is limited according to the project size, that is, the number of files supposed to be analyzed. However, it currently does not rely on the [file-filtering logic of the analyzer](https://github.com/SonarSource/SonarJS/blob/master/sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/filter/JavaScriptExclusionsFileFilter.java). As a result, files from `node_modules` (among other things) are incorrectly included in the counting.

Reported in https://discuss.sonarsource.com/t/sonarlint-not-showing-javascript-issues-when-certain-dependancies-are-included/15800

### PR DESCRIPTION
**Pull request by yassin-kammoun-sonarsource**
Fixes #4187

### CODE REVIEW

File: sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/sonarlint/SonarLintTypeCheckingFilter.java [hunk 1]
```diff
@@ -0,0 +1,125 @@
...
+
+    @Override
+    public boolean test(Path path) {
+      return extensions.stream().anyMatch(ext -> path.toString().endsWith(ext));
+    }
+  }
+
+  static class PathFilter implements Predicate<Path> {
+
+    private static final String[] EXCLUSIONS_DEFAULT_VALUE = new String[] {
```
Comment (vdiez) [inline sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/sonarlint/SonarLintTypeCheckingFilter.java:86]: probably we should move this to `JavaScriptPlugin` class, as it's also used in PathAccessor?

**Review by vdiez — APPROVED** [review]

File: sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/sonarlint/SonarLintTypeCheckingFilter.java (hunk 1 above)
Comment (yassin-kammoun-sonarsource) [reply sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/sonarlint/SonarLintTypeCheckingFilter.java:86]: Good point!
