### PR TITLE
In case of failure log only once

### LINKED ISSUE #1207: ESLint sensor should not attempt to start server if it failed previously
ESLint sensor will try to start server on every analysis if it is not started yet. In case of missing Node.js this means that we will attempt to start (and fail) on every keystroke in VSCode. See also https://jira.sonarsource.com/browse/SLVSCODE-63

### PR DESCRIPTION
**Pull request by saberduck**
Fixes #1207

### CODE REVIEW

File: sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/EslintBasedRulesSensorTest.java [hunk 1]
```diff
@@ -318,14 +321,31 @@ public void should_detect_unknown_rule_key() throws Exception {
 
   @Test
   public void handle_missing_node() throws Exception {
-    doThrow(new NodeCommandException("Exception Message", new IOException())).when(eslintBridgeServerMock).startServerLazily(any());
+    EslintBridgeServerImpl eslintBridgeServer = new EslintBridgeServerImpl(NodeCommand.builder(), tempFolder);
+    eslintBridgeServer = spy(eslintBridgeServer);
+    doThrow(new NodeCommandException("Exception Message", new IOException())).when(eslintBridgeServer).deploy();
```
Comment (vilchik-elena) [inline sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/EslintBasedRulesSensorTest.java]: why did you change throw method from `startServerLazily` for `deploy`?

File: sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/EslintBasedRulesSensorTest.java [hunk 2]
```diff
@@ -318,14 +321,31 @@ public void should_detect_unknown_rule_key() throws Exception {
 
   @Test
   public void handle_missing_node() throws Exception {
-    doThrow(new NodeCommandException("Exception Message", new IOException())).when(eslintBridgeServerMock).startServerLazily(any());
```
Comment (vilchik-elena) [inline sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/EslintBasedRulesSensorTest.java]: I think we can inline `eslintBridgeServerMock` into `createSensor`

File: sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBasedRulesSensor.java [hunk 3]
```diff
@@ -103,7 +103,7 @@ public void execute(SensorContext context) {
       }
       progressReport.stop();
     } catch (NodeCommandException e) {
-      LOG.error(e.getMessage(), e);
+      LOG.debug(e.getMessage());
```
Comment (vilchik-elena) [inline sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBasedRulesSensor.java]: So we will log twice the same thing? Can we think of a better solution?

File: sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImpl.java [hunk 4]
```diff
@@ -129,12 +131,21 @@ private void initNodeCommand(SensorContext context, File scriptFile) {
 
   @Override
   public void startServerLazily(SensorContext context) throws IOException {
-    if (isAlive()) {
-      LOG.debug("SonarJS eslint-bridge server is up, no need to start.");
-      return;
+    if (failedToStart) {
+      throw new NodeCommandException("Failed to start SonarJS eslint-bridge before, will not attempt again.");
```
Comment (vilchik-elena) [inline sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImpl.java]: How about rephrasing? e.g. `Skipping start of eslint-bridge server due to the failure during first analysis`

File: sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/EslintBasedRulesSensorTest.java (hunk 1 above)
Comment (saberduck) [reply sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/EslintBasedRulesSensorTest.java]: because exception is now logged inside `EslintBridgeServerImpl` , so it can't be mocked anymore and we need a real instance. So the failure is mocked in the `deploy` method. I agree that this is not a unit test anymore, but more like integration test between sensor and server, but I didn't find better solution

File: sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImpl.java (hunk 4 above)
Comment (saberduck) [reply sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImpl.java]: I think I will just let you write all the messages for me, it's gonna be faster :)

File: sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/EslintBasedRulesSensorTest.java (hunk 2 above)
Comment (saberduck) [reply sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/EslintBasedRulesSensorTest.java]: I don't understand what you mean, inline how?

File: sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBasedRulesSensor.java (hunk 3 above)
Comment (saberduck) [reply sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBasedRulesSensor.java]: well, I didn't find anything better, without making it much more complicated. And note that we will log twice only in very specific case, when we fail first time the analysis, on subsequent invocation it will not happen (an once it's on error and otherwise on debug level)
