### PR TITLE
Add quick fix for S4322 ('prefer-type-guard')

### LINKED ISSUE #3024: Add quick fix for S4322: Type guards should be used
SonarJS rule.

### PR DESCRIPTION
**Pull request by yassin-kammoun-sonarsource**
Fixes #3024

### CODE REVIEW

File: eslint-bridge/src/rules/prefer-type-guard.ts [hunk 1]
```diff
@@ -121,11 +125,37 @@ function checkCastedType(
...
+  const suggestions: Rule.SuggestionReportDescriptor[] = [];
+  let fix: (fixer: Rule.RuleFixer) => Rule.Fix;
+  if (node.returnType) {
+    fix = fixer => fixer.replaceText(node.returnType as unknown as estree.Node, `: ${predicate}`);
+  } else {
+    const functionBody = node.body as estree.Node;
+    const closingParenthesis = context
+      .getSourceCode()
+      .getTokenBefore(functionBody, token => token.value === ')')!;
+    const openingBracket = context
```
Comment (vilchik-elena) [inline eslint-bridge/src/rules/prefer-type-guard.ts:148]: it's `brace`

File: eslint-bridge/src/rules/prefer-type-guard.ts [hunk 2]
```diff
@@ -121,11 +125,37 @@ function checkCastedType(
...
+      .getSourceCode()
+      .getFirstToken(functionBody, token => token.value === '{')!;
+    const [, begin] = closingParenthesis.range;
+    const [end, _] = openingBracket.range;
+    fix = fixer => fixer.replaceTextRange([begin, end], `: ${predicate} `);
```
Comment (vilchik-elena) [inline eslint-bridge/src/rules/prefer-type-guard.ts:153]: I think it's more reliable to use `insertTextAfter` to rely only on closing parenthesis

**Review by vilchik-elena — CHANGES_REQUESTED** [review]

File: eslint-bridge/src/rules/prefer-type-guard.ts (hunk 2 above)
Comment (yassin-kammoun-sonarsource) [reply eslint-bridge/src/rules/prefer-type-guard.ts:153]: Good point.

**Review by vilchik-elena — APPROVED** [review]
