### PR TITLE
Fix FP on S2424 with TypeScript Enum constants

### LINKED ISSUE #2415: Fix FP on S2424 with TypeScript Enum constants
The rule should ignore Enum constants that override JavaScript standard built-in objects.

### PR DESCRIPTION
**Pull request by yassin-kammoun-sonarsource**
Fixes #2415

### CODE REVIEW

File: eslint-bridge/src/rules/no-built-in-override.ts [hunk 1]
```diff
@@ -45,17 +46,24 @@ export const rule: Rule.RuleModule = {
       scope.childScopes.forEach(checkScope);
     }
 
+    function isTSEnumMemberId(node: estree.Identifier) {
+      const id = node as TSESTree.Identifier;
+      return id.parent?.type === 'TSEnumMember' && id.parent.id === id;
```
Comment (saberduck) [inline eslint-bridge/src/rules/no-built-in-override.ts:51]: why do we need `id.parent.id === id` ? it seems not to be covered by tests

**Review by saberduck — CHANGES_REQUESTED** [review]

File: eslint-bridge/src/rules/no-built-in-override.ts (hunk 1 above)
Comment (yassin-kammoun-sonarsource) [reply eslint-bridge/src/rules/no-built-in-override.ts:51]: Indeed. I thought that both `Err` and `Error` in `enum E { Err = Error++ }` had the same `TSEnumMember ` parent, but it's obviously not the case.

**Review by saberduck — APPROVED** [review]
