### PR TITLE
Fix analysis of TypeScript .vue files

### LINKED ISSUE #2626: Fix analysis of TypeScript `.vue` files
Due to the [caching mechanism](https://github.com/typescript-eslint/typescript-eslint/blob/b1d44497ddf8ef4615c727fe4241e54f7f1aba65/packages/typescript-estree/src/create-program/createWatchProgram.ts#L40) inside the parser we use (TypeScript-ESLint parser) if the first TypeScript file analyzed is not `.vue`, it will not be further possible to analyze`.vue` files as it's not part of default extensions. Following error is logged for SonarJS 7.4
```
19:49:02.119 ERROR: Failed to analyze file [src/App.vue]: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: src/App.vue.
The file must be included in at least one of the projects provided.
``` 

Note that on earlier versions of SonarJS log might be different and misleading:
```
10:37:50.575 ERROR: Failed to parse file [src/App.vue] at line 13: Unexpected token (6:51)
```

TypeScript-ESLint parser expects a [extraFileExtensions](https://github.com/typescript-eslint/typescript-eslint/blob/1c1b572c3000d72cfe665b7afbada0ec415e7855/packages/parser/README.md#parseroptionsextrafileextensions) option to consider additional file extensions as part of TypeScript Program compilation. The introduction of TypeScript analysis support within Vue.js Single File Components [required providing such an option](https://github.com/SonarSource/SonarJS/blob/98601129c049a67155ee0af7dacad512f1eb67c7/eslint-bridge/src/parser.ts#L159). Yet when parsing of non-vue files this option was not provided. 

Reported on community (see [1](https://community.sonarsource.com/t/vue-typescript-fails-to-parse-files-with-required-props-syntax/41709/13),[2](https://community.sonarsource.com/t/general-advice-on-setup-resolving-issues/39012/8))

### PR DESCRIPTION
**Pull request by vilchik-elena**
Fixes #2626

### CODE REVIEW

File: eslint-bridge/src/parser.ts [hunk 1]
```diff
@@ -93,6 +93,7 @@ export function parseTypeScriptSourceFile(
     const result = tsParser.parseForESLint(fileContent, {
       ...PARSER_CONFIG_MODULE,
       filePath,
+      extraFileExtensions: ['.vue'],
```
Comment (vilchik-elena) [inline eslint-bridge/src/parser.ts:96]: I decided to simply add this option here without any refactorings. I believe one big refactoring is required for this file as there are a lot of duplications

File: its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/VueAnalysisTest.java [hunk 2]
```diff
@@ -131,29 +131,26 @@ public void tsWithinVueAsTypeScript() {
...
+
+    // test added for https://github.com/SonarSource/SonarJS/issues/2626 but not actually testing it as order of analysis is not reliable
+    // still we prefer to keep more real-life vue project with another file and tsconfig
+    List<Issues.Issue> issuesList = getIssues(vueFileKey);
     assertThat(issuesList).hasSize(1);
     assertThat(issuesList.get(0).getRule()).isEqualTo("typescript:S3923");
-  }
 
-  @Test
-  public void metricsForTypeScript() {
```
Comment (vilchik-elena) [inline its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/VueAnalysisTest.java:140]: No need to perform the same analysis twice so I moved assertions

File: eslint-bridge/src/parser.ts (hunk 1 above)
Comment (saberduck) [reply eslint-bridge/src/parser.ts:96]: makes sense. I agree that this needs refactoring!

**Review by saberduck — APPROVED** [review]
