### PR TITLE
Fix FN on S5247 for Mustache.escape assignment

### LINKED ISSUE #2348: Fix FN on S5247 for Mustache.escape assignment
We should raise issues on the following snippet, even with the `Mustache` import missing.
```
var template = document.getElementById('template').innerHTML;
Mustache.escape = function(text) {return text;}; // FN
var rendered = Mustache.render(template, { name: inputName });
document.getElementById('target').innerHTML = rendered;
```
As it could be embedded in something such as:
```
<script src="https://unpkg.com/mustache@latest"></script>
<script>
the snippet above
</script>
```

### PR DESCRIPTION
**Pull request by ilia-kebets-sonarsource**
Fixes #2348

### CODE REVIEW

**Comment by ilia-kebets-sonarsource** [comment]
@victor-diez-sonarsource There are 2 separate commits:
- the first fixes the FN
- the 2nd converts the test file into comment-based

File: eslint-bridge/src/linting/eslint/rules/disabled-auto-escaping.ts [hunk 1]
```diff
@@ -131,14 +132,30 @@ export const rule: Rule.RuleModule = {
...
       },
     };
   },
 };
+
+function isMustacheIdentifier(node: estree.Node) {
+  return isIdentifier(node) && node.name === 'Mustache';
+}
+
+function isMustachModule(context: Rule.RuleContext, node: estree.Node) {
```
Comment (victor-diez-sonarsource) [inline eslint-bridge/src/linting/eslint/rules/disabled-auto-escaping.ts:158]:
```suggestion
function isMustacheModule(context: Rule.RuleContext, node: estree.Node) {
```

**Review by victor-diez-sonarsource — APPROVED** [review]
just some small typo, the rest LGTM
