### PR TITLE
Disable ucfg rule for JS embedded in HTML files

### LINKED ISSUE #4036: Do not generate UCFGs for JavaScript code inside HTML
Generating correct UCFGs for HTML would require a job similar to [what was done for YAML in sonar-security](https://github.com/SonarSource/sonar-security/commit/14251a6e51d210d268fa71abbac40e4996d03227).

We are wrongly generating UCFGs for JavaScript code embedded inside HTML files. This is due to the fact that the analysis of JavaScript code inside HTML is reusing the same logic as the analysis of JavaScript code inside YAML. Since we haven't implemented yet the support for analyzing injection vulnerabilities of JavaScript code inside HTML, we are needlessly generating UCFGs which not only waste resources on the security analyzer but also fill the JavaScript analyzer's cache for nothing. 

Incidentally, these useless generated UCFGs for JS inside HTML cause failures when reading back these UCFGs from the analyzer's cache. The root cause of these failures is a separate issue to be investigated further.

https://community.sonarsource.com/t/getting-error-failure-when-reading-cache-entry-with-github-actions-but-scan-completes-as-success/95769/3

### PR DESCRIPTION
**Pull request by ilia-kebets-sonarsource**
Fixes #4036

### CODE REVIEW

**Review by yassin-kammoun-sonarsource — CHANGES_REQUESTED** [review]
I think we need an integration test for this change.

**Comment by ilia-kebets-sonarsource** [comment]
Dropping this, because we haven't found the source of the issue that was initially raised in community.

File: its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/HtmlSecurityTest.java [hunk 1]
```diff
@@ -0,0 +1,106 @@
...
+
+    var result = orchestrator.executeBuild(getScanner(projectPath, projectKey));
+    assertThat(result.isSuccess()).isTrue();
+
+    var stream = Files.find(
+      projectPath.toPath().resolve(".scannerwork"),
+      3,
+      BuildResultAssert::isUcfgFile
+    );
+    assertThat(stream.toList().isEmpty()).isTrue();
```
Comment (yassin-kammoun-sonarsource) [inline its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/HtmlSecurityTest.java:64]: Can we get rid of `isTrue` and move `isEmpty`?

File: its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/HtmlSecurityTest.java [hunk 2]
```diff
@@ -0,0 +1,106 @@
...
+      .addPlugin(JAVASCRIPT_PLUGIN_LOCATION)
+      .setEdition(Edition.DEVELOPER)
+      .activateLicense()
+      .addPlugin(MavenLocation.of("com.sonarsource.security", "sonar-security-plugin", "DEV"))
+      .addPlugin(
+        MavenLocation.of("com.sonarsource.security", "sonar-security-js-frontend-plugin", "DEV")
+      )
+      .addPlugin(
+        MavenLocation.of("org.sonarsource.config", "sonar-config-plugin", "LATEST_RELEASE")
+      )
```
Comment (yassin-kammoun-sonarsource) [inline its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/HtmlSecurityTest.java:82]: I think we can remove this because it was introduced for YAML language detection.

File: its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/YamlSecurityTest.java [hunk 3]
```diff
@@ -0,0 +1,105 @@
...
+
+    var result = orchestrator.executeBuild(getScanner(projectPath, projectKey));
+    assertThat(result.isSuccess()).isTrue();
+
+    var stream = Files.find(
+      projectPath.toPath().resolve(".scannerwork"),
+      3,
+      BuildResultAssert::isUcfgFile
+    );
+    assertThat(stream.toList().size() == 1).isTrue();
```
Comment (yassin-kammoun-sonarsource) [inline its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/YamlSecurityTest.java:64]: To be verified, but I think there should be an assertion method `hasSize`.

**Review by yassin-kammoun-sonarsource — APPROVED** [review]
Great job writing those integration tests.
I left some suggestions about a few assertions.
Looks good to me otherwise!
