### PR TITLE
Fix FP S107 ('sonar-max-params'): Ignore Angular component constructors

### LINKED ISSUE #3160: Fix FP S107 ('sonar-max-params'): Ignore Angular component constructors
| Label | Description |
| --- | --- |
| Context | All products |
|Rule | S107 "Functions should not have too many parameters" |
|Reproduce | False positive on Angular projects using components with multiple dependencies.<br> See the sample project created by community user, in particular the file: https://github.com/Mr1upMachine/1up-ng-too-many-parameters/blob/9438105202d39e1df9d830a592a165e8b4bb60b9/src/app/app.component.ts |
| Community | https://community.sonarsource.com/t/add-exclude-name-regex-to-functions-should-not-have-too-many-parameters/50333/7 |

### Explanation
Angular uses _Dependency Injection_ for user classes that derive from Angular's `Component` class.
In this case, arguments passed to `constructor` include all the dependencies used by the user's component.
It is common to have many dependencies/arguments and the user does not always control the amount.
See community thread for more details.

### Proposed improvement
When applying S107 rule, exclude `constructor` methods on users classes that extend Angular `Component` class.

### PR DESCRIPTION
**Pull request by yassin-kammoun-sonarsource**
Fixes #3160

### CODE REVIEW

**Comment by yassin-kammoun-sonarsource** [comment]
[RSPEC update](https://github.com/SonarSource/rspec/pull/1292)

File: eslint-bridge/src/linting/eslint/rules/sonar-max-params.ts [hunk 1]
```diff
@@ -47,8 +48,51 @@ export const rule: Rule.RuleModule = {
...
+          function isConstructor(
+            node: TSESTree.Node | undefined,
+          ): node is TSESTree.MethodDefinition {
+            return (
+              node?.type === 'MethodDefinition' &&
+              isIdentifier(node.key as estree.Node, 'constructor')
+            );
+          }
+
+          function isComponent(node: TSESTree.Node | undefined) {
```
Comment (ilia-kebets-sonarsource) [inline eslint-bridge/src/linting/eslint/rules/sonar-max-params.ts:82]: rename to `isAngularComponent`?

File: eslint-bridge/src/linting/eslint/rules/sonar-max-params.ts [hunk 2]
```diff
@@ -47,8 +48,51 @@ export const rule: Rule.RuleModule = {
...
+            return false;
+          }
+
+          /** A component is represented as ClassDeclaration > ClassBody */
+          const maybeComponent = maybeConstructor.parent?.parent;
+          if (!isComponent(maybeComponent)) {
+            return false;
+          }
+
+          return true;
```
Comment (ilia-kebets-sonarsource) [inline eslint-bridge/src/linting/eslint/rules/sonar-max-params.ts:71]: Kudos for early returns!

File: eslint-bridge/tests/linting/eslint/rules/sonar-max-params.test.ts [hunk 3]
```diff
@@ -118,5 +128,32 @@ ruleTester.run(``, rule, {
         },
       ],
     },
+    {
+      code: `
+      import { NotComponent } from '@angular/core';
+      import { Component } from 'fake-angular';
```
Comment (ilia-kebets-sonarsource) [inline eslint-bridge/tests/linting/eslint/rules/sonar-max-params.test.ts:134]: `'not-angular-core'`?

File: eslint-bridge/tests/linting/eslint/rules/sonar-max-params.test.ts [hunk 4]
```diff
@@ -50,6 +50,16 @@ ruleTester.run(``, rule, {
       code: `class C { constructor(private a: any, public b: any) {} }`,
       options: [MAX_PARAMS_5],
     },
+    {
```
Comment (ilia-kebets-sonarsource) [inline eslint-bridge/tests/linting/eslint/rules/sonar-max-params.test.ts:53]: Are you motivated to rewrite this to the comment-based framework, as Victor did? https://github.com/SonarSource/SonarJS/pull/3420/files#diff-42a17f048a9c3ed1bf76f0985b81f2c2c12da95966bf21c55d2fb9f43dd635f2R1

Comment (yassin-kammoun-sonarsource) [reply eslint-bridge/tests/linting/eslint/rules/sonar-max-params.test.ts:53]: We can't because the rule relies on the context options, which the framework doesn't support.
