### PR TITLE
Don't throw exception when missing tsconfig

### LINKED ISSUE #2498: NodeCommandException should only be used when Node fails
We started to use `NodeCommandException` for some issues which are not fatal. This breaks contract with SonarLint and causes UX issues. 

> Reusing this exception for other erroneous cases, like tsconfig.json not being found, resulted in a significant degradation of the user experience: instead of an exception being thrown at most once, we get it at each analysis - so each keystroke in the worst case scenario.

More info https://discuss.sonarsource.com/t/degraded-ux-in-sonarlint-due-to-reuse-of-nodecommandexception/6998

### PR DESCRIPTION
**Pull request by saberduck**
Fixes #2498

### CODE REVIEW

File: sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/TypeScriptSensor.java [hunk 1]
```diff
@@ -108,7 +107,13 @@ void analyzeFiles() throws IOException, InterruptedException {
     ProgressReport progressReport = new ProgressReport("Progress of TypeScript analysis", TimeUnit.SECONDS.toMillis(10));
     List<InputFile> inputFiles = getInputFiles();
     eslintBridgeServer.initLinter(rules, environments, globals);
-    List<String> tsConfigs = tsConfigs();
+    List<String> tsConfigs = new TsConfigProvider(tempFolder).tsconfigs(context);
+    if (tsConfigs.isEmpty()) {
+      // This can happen in SonarLint context where we are not able to create temporary file for generated tsconfig.json
+      // note that JS files work even without generated tsconfig, perhaps we could do same for TS
```
Comment (yassin-kammoun-sonarsource) [inline sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/TypeScriptSensor.java:113]: I think we can remove this comment here (i.e. the part with `note that...`) and create a ticket instead to materialise this investigating task.

**Review by yassin-kammoun-sonarsource — APPROVED** [review]
